### ISSUE TITLE
Partner Pages

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#10]
The Project Partners would like something that reflects their organisations on the website, and I thought the paragraph written by LMA could serve as a good model for you to use. Thanks

Credits, Links and Acknowledgement

All content provided by LMA, including the maps, photographs, plans, film clips and Street Index data will be clearly credit LMA as the source of the content and provide onward links to LMA to ensure that researchers are able to continue their work in the LMA collections.

Links to LMA websites, including the Collage image database, will be provided within the Layers of London site and a partner page will be provided for LMA to provide a summary of the included collections and how to continue researching with LMA

**Comment by martincf** [comment]
This can be added into the Partners & Supporters page under About in the marketing site, via the CMS.
