### ISSUE TITLE
Image copyright CC BY-SA 4.0

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#103]
Images and photos uploaded to the site to be auto watermarked with the _CC BY-SA 4.0_ statement or Logo (see attached)? 

![image](https://user-images.githubusercontent.com/6515338/40072485-f098f85c-586b-11e8-9205-444773a9d5df.png)

See the example from Open Benches https://openbenches.org/bench/5922

**Comment by Forester1** [comment]
Update:
The licence that we require is the _Attribution-NonCommercial-NoDerivatives 4.0 International_ https://creativecommons.org/licenses/by-nc-nd/4.0/

The code snippets for the icons (watermarked if possible) is available at https://creativecommons.org/choose/ or alternatively

**Normal Icon**
`<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.`

**Compact Icon**
`<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.`

@selrashidi

**Comment by edtjones** [comment]
Thanks for this @Forester1 - good stuff.

**Comment by edtjones** [comment]
@forester1 regarding watermarking - while this is doable, from a discussion with Seif I understand it’s only one partner who requires this, and you’ll be getting the images in bulk. Is it sufficient to do this as a bulk offline exercise before they’re presented on the site? Much easier to write a script to do it in bulk than implement for every uploaded image on the site.

**Comment by edtjones** [comment]
Supplementarily, that licence will require us to watermark the attribution in as well. Is that expected?
