### ISSUE TITLE
Volunteers Page

### ISSUE THREAD

**Issue by KFlynn1** [layersoflondon/application#105]
Could we have a separate Volunteers Page with space to update content, link to factsheets and an expression of interest form, and set challenges. Also would it be possible to embed an external event planning page?

**Comment by Forester1** [comment]
Layers of London Volunteer page requires: 
- Page update content 
- link to factsheets and educationa materials
- an expression of interest form
- Place to set and advertise challenges: https://www.museummakers.co.uk/get-involved/donate-a-day/. 
- Ability to save/Accept challenges

Also would it be possible to embed an external event planning page? (For example https://www.meetup.com/) 

@KFlynn1

**Comment by KFlynn1** [comment]
Is there an update regarding whether this is possible, is this something I can do once the team has admin rights? @edtjones

**Comment by martincf** [comment]
Hi @KFlynn1 ... is this issue now resolved? I presume content is now going into the marketing website area, specifically, in the Get Involved section.

**Comment by KFlynn1** [comment]
Hi @martincf yes this is all fine, thanks
