### ISSUE TITLE
Trails and Polygons

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#11]
In our weekly meeting this morning we discussed two separate but somehow related things

1. Trails - please don't forget these as they are quite important.
2. The ability for users to create polygons. (for example an allotment, or to define a park or a parish). Will this be possible?

**Comment by martincf** [comment]
Trails are in the technical roadmap. Polygons I would suggest are much later down the road.

**Comment by selrashidi** [comment]
Mark is of the view that for the trails, an automated route between the points would be good. Can we factor that into our thinking please.
