### ISSUE TITLE
Map width

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#110]
Map window – we’d prefer a 50:50 split as part of the aim is for people to explore the map and it’s too squashed at the moment. An alternative would be for it to be manually adjustable within parameters, ie no more than a 1/3 2/3 split either way?

**Comment by andyError** [comment]
I've gone for 45/55, which feels better.

**Comment by Forester1** [comment]
Is this still adjustable?

**Comment by martincf** [comment]
What are you thinking, Hendrik? :)

**Comment by Forester1** [comment]
Recommend closing as moved to beta
