### ISSUE TITLE
Logo anchor click target is too small

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#112]
(Report from @selrashidi )

Although you can click the logo on the content-managed pages to go home, the click target is smaller than the logo so it's not obvious. Screenie attached showing outline of anchor at the moment.
![screen shot 2017-02-03 at 10 38 47](https://cloud.githubusercontent.com/assets/4377783/22588288/0b4f93ce-e9fd-11e6-83c0-e77ad1dff644.png)

**Comment by foxpaul** [comment]
The nav bar was covering half the clickable area so i've fixed that
