### ISSUE TITLE
Theme/types tagging of records

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#113]
We need to discuss how notes [records!] can be tagged with the different ‘Types’ and ‘Themes’ – not clear how this happens?

**Comment by andyError** [comment]
It will probably need to be added to the Add Record form.

**Comment by Forester1** [comment]
Will also need to be considered in parallel to the broader issue of metadata and standards especially when considering themes. UKAT http://www.ukat.org.uk/ is the standard that our partners use and are starting to supply data in. 
What is key is:
-Keywords
-Themes/sub-themes
-Titles

Thanks

**Comment by Forester1** [comment]
Can we also tie this in with the Meta Keywords and Meta Description from the CMS please

**Comment by mpdavies** [comment]
There ought also to be a discussion/agreement on a list of themes and types to sense-check them in relation to the kinds of things that users will be working on

**Comment by martincf** [comment]
Attaching a relevant recent wireframe that was created for the Add Record page. It shows the addition of a theme dropdown and tag generator for the user to include those two elements to their content.
[Add record.pdf](https://github.com/layersoflondon/application/files/2145582/Add.record.pdf)

(This wireframe is taken from V7.5 – 28/06/18)

**Comment by Forester1** [comment]
Linked to Searching and taxonomies #9

**Comment by Forester1** [comment]
RE: Add Record.pdf
_Help us categorise your record_
Really like this @martincf 

_Add some tags_
Good. Can we add in both suggested tags and manual tag entries please

**Comment by Forester1** [comment]
Feedback on beta:
_Record themes and taxonomies are incredibly important (linked to search and keywords). Keen to see this working using the previously provided LMA categories, included in the advanced search and how it will work with the new search. Also needs adding to the create Record as an optional attribute_
