### ISSUE TITLE
Advice on image specification and performance

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#114]
We have a need to present the images uploaded to pins on the site at a specific resolution (for example 72dpi 1000px). If there is a need for images with a larger pixel dimension to appear on the site, it is preferential to limit any downloads to the previous lower resolution. 

Is there a functionality setting to allow for this? If not can we discuss please.

The need for the CC BY-SA 4.0 statement watermark has also been reiterated.

Linked to ticket _Image copyright CC BY-SA 4.0 #103_

**Comment by Forester1** [comment]
@edtjones Can we get an update on this as it is coming up a lot with partners

**Comment by edtjones** [comment]
We can resize, no problem. But we need 1200px max width to accommodate bigger screens. This is probably ok isn't it? It wouldn't be sufficient for print-quality.

**Comment by edtjones** [comment]
(and yes to watermarking as per #103 )

**Comment by andyError** [comment]
No action here.
