### ISSUE TITLE
Final data migration

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#115]
Data and process for the transfer of content from http://alpha.layersoflondon.org/ to the new site.
This needs to be prior to any live site to allow QA and testing on the data migration. This is required also so that we can confirm with users who are preparing new content that it should be loaded onto alpha and guaranteed to transfer in the migration to the new site.
This is also to include blog content http://alpha.layersoflondon.org/blog
 
This is linked to ticket _Bug testing period #101_

@amytodd

**Comment by edtjones** [comment]
@Forester1 I'm fine-tuning a script to move everything across. It's idempotent so we can run as many times as we like - at the point of cutover we'll do a final migration.

Ed

**Comment by Forester1** [comment]
Thanks @edtjones. Good to know QA will be undertaken before final migration.
