### ISSUE TITLE
Limiting map layer zoom

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#116]
We have a series of maps/plans that requires the zoom level of the visibility of the map layer to be specified. What is the process for specifying a min and max scale for specific layers?

**Comment by andyError** [comment]
This is probably technically possible, but seeing as users can do things like apply multiple layers, it would be difficult or unintuitive in practice. I think it's preferable to allow users to zoom right in, even if the quality is comprised at higher zoom levels.
