### ISSUE TITLE
Zoom in Selection causes the map to move and the overlay to disappear

### ISSUE THREAD

**Issue by anacf** [layersoflondon/application#117]
To view this issue: 
1. select map overlay RAF.
2. Find the pin Barking Park and zoom into a large size.
3. select and deselect the overlay RAF map. 

The overly will either not show; or the view will jump to a totally different part of the map.

**Comment by edtjones** [comment]
@anacf this is sort of by design. If you're zoomed in somewhere and click an overlay, it seems reasonable to pan the map to the location of that overlay.

Let's review in phase 2. Will add a wishlist item here: https://github.com/layersoflondon/application/projects/3
