### ISSUE TITLE
Analytics: Give Chris email addresses of people that need access to GA, GTM and Search Console

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#121]
Adminstrator access for the website analytics for the Layers of London Team. This is required for both customer insight purposes and SEO for the various site sections.
@amytodd @KFlynn1

**Comment by chrisunitt-xx** [comment]
I've set this up, so if you assign this to me and send the relevant email addresses and I'll sort it.

**Comment by edtjones** [comment]
Did we add a snippet for you @chrisunitt-xx ? (can you accept the pending membership invite to this org so I can assign tickets to you?

**Comment by chrisunitt-xx** [comment]
Can someone send me the email addresses I need to give access to GA, GTM and Search Console?

Also, I've set these things up but will need to transfer ownership to someone (or, ideally a 'master' email address that isn't specific to one person) at some point.

**Comment by andyError** [comment]
@amytodd Can you hook Chris up with these? Ask here if you need any more info.

**Comment by amytodd** [comment]
Hi Chris, I suppose Seif and Olwen for now? Thanks

Amy Todd
Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)
The Centre for Metropolitan History,
The Institute of Historical Research,
Senate House, London WC1E 7HU
t: 02078628765
e: amy.todd@sas.ac.uk
Twitter: @LayersofLondon
________________________________

**Comment by chrisunitt-xx** [comment]
Thanks @amytodd I've done that. Seif and Olwen are able to add further users too.

A note for someone's to do list: At some point the Google Analytics, Tag Manager and Search Console accounts will need to be transferred over to someone who's not me.

**Comment by edtjones** [comment]
Can you add hosting@error.agency Chris? 

--
Sent from my phone: please forgive the brevity.

Ed Jones
