### ISSUE TITLE
Alpha migration data quality questions

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#126]
@selrashidi @Forester1 @amytodd I've been working on the migration of data from the alpha to beta sites. There are a couple of things we need to think about - ideas welcome:

- Some pins have MS Word documents associated with them which are in an old format, and so can't be opened on modern versions of Word. What should we do about these?
- At least one pin has a 'from' date in the future. I assume this is a mistake; should we enforcing 'from' dates in the past?

I'll add more to this ticket as they arise.

Ed

**Comment by Forester1** [comment]
Hi Ed
.doc format Word documents should be fine as they can can be imported or transformed. As long as they are still accessible format and not corrupted most word processing software should handle .doc. We can make recommendations as part of the uploading but apart from that this is difficult to police. I would leave them as they are.

Dates: Well spotted. Limiting date range to today's date may be a solution. Is this possible?

**Comment by Forester1** [comment]
Relevant to ticket Final data migration #115
