### ISSUE TITLE
Inviting a user to a team

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#127]
When inviting a user to a team the following error message appears. The user does not get added to the team and they are not notified of the invitation
![image](https://user-images.githubusercontent.com/6515338/41419133-2ebbede4-6fe9-11e8-93e2-544acebf207b.png)

@amytodd

**Comment by martincf** [comment]
Trying to ascertain if this a bug from the Alpha site or not? The screenshot is from the alpha site. If so, we'll close this issue.

**Comment by amytodd** [comment]
Yes it is – so not an issue anymore

Thanks
