### ISSUE TITLE
Prototype website - feedback March 22

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#13]
Hi All
This is a list of issues/queries we have collated. We think it looks great. Some of these are things that just need fixing, but most are queries about what might be possible or are things that are confusing or unclear.

•	Under ‘Search’ – I don’t understand what the tick box ‘ only search in area shown on map’ means – map window extent? Base map? Clarify this?
•	Also on the ‘Search’ page there’s a message ‘You can set a date range too by clicking on the clock icon in the tool bar – this is OK for someone just searching by date, but need also to have this on the search page so that someone can search by place and date at the same time
•	Need a button (or back button) that will cancel previous search results and restore to default
•	Need to explain that search results are either in the tray or appear as purple dots on the map;  opening and closing the results ‘tray’ needs to be explained as well
•	Clicking on one of the search results: –  
•	can add it to a collection. Clarify that a Public collection can be added to by anyone and Private Collection is closed? I think that’s right?
•	Create collection – the wording of what makes  collection private isn’t very clear
•	a thumbnail of place’s location on map (showing coordinates is good) – will this thumbnail be clickable back to the map so that the user can see what else is close by
•	When adding a new pin, there is an option to add it to a collection. At present a user can click on both your collection and public collection. Is this intentional? 
•	Could date search and map layers appear as dropdown menu on left navigation  – rather than opening a new page (just seems a bit clunky)? Recognise that probably be too many layers/periods to do this efficiently. The separate layers tool is good although it needs to be pointed out that this is where the opacity of a layer is controlled. 
•	I know we keep mentioning this, but we need to be able to display the additional layers from each of the historic maps: parish boundaries, ward boundaries, street layouts, places. So the design needs to have these either as equivalent layers to the maps themselves, or as ‘sub-layers’. So users could compare the street network in 1682 and 1827, along with a map image of their choice. This has implications for how they are listed displayed so needs to be catered for soon.
•	Each pin/search result has an image – what if the pin creator hasn’t added an image – ie the pin just contains text or sound. What will appear instead – project logo? Standard image?
•	If the contributor’s name is clicked on a pin will the user see all the pins that contributor has added?
•	If the ‘tray’ is closed and a user hovers over the left hand tool bar, the arrow to pull the tray out is covered up
•	Not quite sure what a search box is doing in the pop-up layers selection screen? Implies that you can search the layers, perhaps? In due course that may be possible via gazetteers extracted from the maps, but there’s a problem to be solved in terms of how to include those results as they don’t relate to uploaded content.
•	Date range: eras need to be in chronological order. World War 2 is missing. And we should have an option for ‘Roman and pre-Roman’.
•	Add Record. Needs to have a check box so that users agree with the T&Cs – eg Creative Commons sharing, that they are the copyright holder or have permission from the copyright holder etc.. Embed a link to a single page with Permissions and Privacy Policy. WE NEED TO DISCUSS
•	There’s no obvious navigation back/across to other areas of the website such as About the project, resources etc. We either need a  Home button taking users to the new front end where these other fuctions will appear as tabs, or have the tabs themselves at the top of the map screen… Not sure which is best – most similar sites seem to ask people to leave the map/content creation part of the site first, but we need to be aware of the need for users to be able to find help. This also brings in the issue of location of teaching resources, help pages, volunteer and group pages etc – is the map basically self-contained and everything is via the home page, or are these other areas of the site navigable from the map page?
•	When you log in, could your own pins be a different colour or highlighted in some way
•	When you log in, it should take you to where you left off last time 
•	Will multiple pins on one point be presented with a numbered pin that you can zoom in on to see individual pins
•	I am wondering if there is a way to make the layers functionality more prominent? I think its a really cool tool thats quite unique and I think you could browse the website and miss it
•	Creating a collection (can we mention something about teachers/class collections to make it really obvious its the same functionality for teams as it is for schools?)

**Comment by mpdavies** [comment]
Oh yes, and we need somehow to build in the 'trails' feature as part of collections

**Comment by martincf** [comment]
We've broken these comments and issues out separately in a Google spreadsheet file (@selrashidi has the link). We're treating this as slightly separate feedback for the initial prototype.
