### ISSUE TITLE
Design & UX: add example placeholder content in Add Record forms

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#130]
From Hendrik:

> **Title:** Can we add in an example title? For example "Trebor sweet factory on Smith Street"

> **Description:** Can we add in an example Description or example descriptions instructions? - Can we insert a basic character limit here (say 10-25 characters) to encourage users to add some more detailed content

**Comment by andyError** [comment]
Closing as dupe of: https://github.com/layersoflondon/application/issues/310
