### ISSUE TITLE
Layers sublayers and metadata

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#138]
Use supplied RAF images metadata to scope out layers sub-layers and associated data representation. Need to wireframe.

**Comment by martincf** [comment]
New layers wireframes for sub-layers are in v7.5 and upwards. Attached here. 

[Wireframes - V7.5 – Layers.pdf](https://github.com/layersoflondon/application/files/2137678/Wireframes.-.V7.5.Layers.pdf)

**Comment by andyError** [comment]
This is related to: https://github.com/layersoflondon/application/issues/271
