### ISSUE TITLE
Records being added to another's collection

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#142]
Investigate the ability for the record creator to remove their record from a collection after it's been added. Does this mean we need factor in an alert for when a record is included in a collection, every time? Like instagram, immediate alerts vs a list of alerts. Put on edit record page ability to remove record from any collection. Alert collection owner of removal. We also need to alert record owner when their record is added to a collection.

**Comment by andyError** [comment]
Feels like unnecessary complexity, and undue noise.
