### ISSUE TITLE
Education pages IA

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#150]
From Amy: Karina and I have been thinking about the education pages/programme.

Page Hierarchy:
•	Learning
•	Schools and teachers/Young people/families
•	Themes: Victorian/Roman etc
•	Relevant map Layer
•	Content on the map (collections made by us? Automagically?)
•	Resources: Factsheets/worksheets/workbooks/curriculum links/suggested activities/PP
•	Image banks (does this replicate the pins and collections?)
•	Project case studies/ guidance

**Comment by Forester1** [comment]
Would be also useful to know the delineation between Error and website admin or end to know who can action what. 
@amytodd @KFlynn1 @martincf
