### ISSUE TITLE
User ability to delete pins

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#151]
From Amy: we want users to be able to edit and delete their pins in case they want to move them/ revise them or just try out the website but we don't want users to delete all their pins if they choose to because we want to retain contributions so content keeps growing on the map

**Comment by martincf** [comment]
during the weekly call (14 July) we suggested this needs to be considered at a policy level. Once a policy has been defined, we can action the necessary steps.

**Comment by andyError** [comment]
There's no action for us here, and this is possibly no longer relevant.
