### ISSUE TITLE
User guides question

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#158]
From Amy: User guides for the website (document outlining how to add a pin etc we can hand out after training and also have them to download on the website - shall we put something together based on our current ones/ amending when the website is relaunched and send to you to okay? Thanks

**Comment by martincf** [comment]
I think that'd be a reasonable way to start. However, it maybe worth comparing to the beta site, now that it's available.

**Comment by andyError** [comment]
Obsolete.
