### ISSUE TITLE
Data collection question

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#159]
Is this something that you will be doing?Hi - I am working on a user agreement for the website and have been speaking with the data protection officer at UoL. he brought up the following: 'If you're doing any collection / analysis / reporting (cookies etc.) on people using the website then that will be something to include separately.'

**Comment by KFlynn1** [comment]
Yes this is something we will be doing

**Comment by Forester1** [comment]
@martincf @KFlynn1 We well still require input from Error on the technology aspect of this.

**Comment by Forester1** [comment]
Relevant to issue Example legal and technical pages (accessibility) #157

**Comment by andyError** [comment]
I'm going to close this, as there's no immediate action for us, and I assume we'll be asked through other channels if needed.
