### ISSUE TITLE
Admin interface overview requirements

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#162]
Outline requirements for an admin interface:

Edit record (content or status)
Assign users to teams
Assign records to collections
Invite new users
Assign collections to teams
Create new layers (with tile URL)
Manage highlight records

I'm sure there are more but this'll do for starters

**Comment by Forester1** [comment]
Thanks @edtjones. Would be useful to know the pros and cons of a separate mgt system. Worth a conversation?

@selrashidi

**Comment by edtjones** [comment]
p.s. We plan to add an 'edit as admin' button on records if you're logged in as an admin.

**Comment by edtjones** [comment]
[LOL admin interface wireframes.pdf](https://github.com/layersoflondon/application/files/2213500/LOL.admin.interface.wireframes.pdf)
@Forester1 some outline wireframes for what we're building in the admin interface. Would be useful to know if there's any major omissions from this. nb that the design / layout will not necessarily be like this; this is more an aide-memoire for developing the functionality

**Comment by Forester1** [comment]
Hi @edtjones , have included a version with comments.
[LOL.admin.interface.wireframes_HG.pdf](https://github.com/layersoflondon/application/files/2213888/LOL.admin.interface.wireframes_HG.pdf). It looks to have all the standard CMS functionality. Will this link into rooftop or is it part of it already?

**Comment by edtjones** [comment]
It won't be part of Rooftop - that's really just a CMS for the content pages. The admin interface will need to be a custom thing because it deals with all the data held locally in the application (as opposed to pulled from Rooftop through an API).

**Comment by Forester1** [comment]
Thanks
