### ISSUE TITLE
Investigate search terms as taxonomies

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#164]
We need to investigate if we can take popular/common search terms and use them as taxonomies.

**Comment by edtjones** [comment]
I assume the search terms would become taxonomy *terms* not taxonomies. But even so, how would we know which taxonomy to assign them to?

Might be better to keep a list of frequent searches

**Comment by Forester1** [comment]
Can this be tied into the themes and keywords associated with the records as they are created? This i can include the previously supplied LMA data standards which are quite sensible and would be a start for practical search terms. Linked to issue  Theme/types tagging of records #113
@selrashidi @amytodd @KFlynn1

**Comment by mpdavies** [comment]
We'll need some detailed discussion of this. In principle it would be great to get content creators to tag records with themes. Most academic researchers are used to doing this for journal articles, research databases etc, but we'd need a bit of help text for volunteers, groups etc. We want a list that's comprehensive but mostly fairly broad terms

**Comment by Forester1** [comment]
To be linked to the previously supplied draft of the proposed metadata _Metadata_LoL_0618_v0.2.doc_

**Comment by andyError** [comment]
I'm going to close this, I think it's been superceded. We'll be using the LMA themes at some point: https://github.com/layersoflondon/application/issues/287
