### ISSUE TITLE
Map: Clustering markers

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#170]
We need to implement the feature whereby a a pin indicates the number of many pins at a more zoomed in state.

**Comment by Forester1** [comment]
Hi
Quick query. Is this referring to the leaflet Cluster marker tool https://github.com/Leaflet/Leaflet.markercluster?

**Comment by edtjones** [comment]
Might not be that plugin, but yes, something similar.

**Comment by edtjones** [comment]
(We might also investigate a vector layer with the cluster counts on, instead)

**Comment by Forester1** [comment]
Thanks @edtjones . Prior to any implementation, can you send through an example, of both if possible, as this is a high priority issue that has ben raised numerous times for users and researchers. Thanks
