### ISSUE TITLE
Med priority: UX - Records created, pins not appearing

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#171]
We've received some feedback from users who are experiencing problems adding pins to collections. For instance, if you search for "rememberher" on http://alpha.layersoflondon.org/the-map 6 results are returned but only 4 have pins. The two listed records with no pins are:  

Lilian Bader (1918-2015)
Helena Normanton, QC (1882-1957)

See image below: 
![image](https://user-images.githubusercontent.com/6515338/42223449-b23cab14-7ecf-11e8-8dec-059278ebabcb.png)

Can you assist?

@amytodd @KFlynn1 @edtjones

**Comment by amytodd** [comment]
Hi all - can we make this a priority as this is a students work and her placement ends fairly soon so if she needs to re-do her work we have limited time

Thanks

**Comment by martincf** [comment]
The pins are there, they're just incredibly close to others in the list, so, zoomed out, you won't see them. If you need to click them, zoom in. On the beta, we'll highlight record map pins when the user hovers over the search result (on tablet and mobile, a click will highlight the map pin.)
