### ISSUE TITLE
Map: can't see content without logging in

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#175]
I can't see any map/record content without being logged in first. 

[From feedback doc: LoL_Beta_Review_v0.2]... the doc actually states it the other way round: no content on map if logged in. @Forester1 can you clarify, please?

**Comment by Forester1** [comment]
Hi

When you are logged in as yourself on the beta (so both the generic beta log in and user account login used) you can't see any records/collections in the left panel. 

Thanks

**Comment by edtjones** [comment]
Can no longer repeat. Think this is a historical issue
