### ISSUE TITLE
Marketing site: change navigation text to 'Learning'

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#178]
Schools, Clubs and Groups to be changed to Learning. 

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by martincf** [comment]
@Forester1 @selrashidi 

What's the thinking behind this request? Is it to truncate the original navigation text? I ask because it's been a while since we agreed to the titling of the navigation and I think it's pretty solid as a descriptive navigation element. Learning is too similar to Help Centre.

**Comment by andyError** [comment]
Done, closing.
