### ISSUE TITLE
Marketing site: Need for embedded PDF viewer for teaching resources

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#179]
> Teaching resources- Need for embedded pdf viewer to be available on the page.

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by Forester1** [comment]
That's great Martin. The main purpose here is for the teaching resource packs to be easily viewed online, easily discovered and downloaded. It may just be methodology, that we can test on the beta, for uploading and publishing project artefacts such as pdf and .doc

**Comment by Forester1** [comment]
Feedback on beta: 
Learning
Teaching resources- Need for embedded pdf viewer to be available on the page asked for again

**Comment by andyError** [comment]
I find this hard to believe. Users can see the whole thing at full size just by clicking the link. Using an embedded viewer will mean trying to view the resource through a letter box on the page. We could just use a better-looking call-to-action on the page perhaps with a thumbnail type preview.

**Comment by andyError** [comment]
Actually, I'm going to close this, it's covered here: https://github.com/layersoflondon/application/issues/272
