### ISSUE TITLE
Marketing site: Footer logos

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#180]
> We require a footer for all pages to display all partner logos. See Figure 1 LoL Footer logos. Logo to be supplied by LoL Project Team	

(Figure 1)
Heritage Lottery Funding logo | Institute of Historical Research logo | Birkbeck, University of Londonlogo | British Library logo | Historic England logo | Museum of London Archaeology logo | London Metropolitan Archive logo | National Archives logo |  

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by Forester1** [comment]
@selrashidi can you please advise on the master versions of the logos?

**Comment by Forester1** [comment]
Hi @andyError @martincf , have sent through example logos in a presentation _Lol_Web_logos.pptx_. They are not in order and excludes the Creative commons logo which also needs to be added ( #181 )

**Comment by martincf** [comment]
Recent email comment from Hannah:

> And regarding the logos in the footer of the beta site: the IHR logo that has been used is out of date. Additionally, and Conor can correct me on this if I am mistaken, I don’t think that we need to have the SAS logo there, as their branding is already in our logo.
> Instead, could you make sure that the current IHR logo is visible, and remove the SAS logo?

**Comment by Forester1** [comment]
Thanks @martincf. 
The order of the footer logos (left-right) are:
Heritage Lottery Funding logo | Institute of Historical Research logo | Birkbeck, University of London logo | British Library logo | Historic England logo | Museum of London Archaeology logo | London Metropolitan Archive logo | National Archives logo | Stavros Niarchos Foundation
@selrashidi

**Comment by andyError** [comment]
![screen shot 2018-08-03 at 15 50 09](https://user-images.githubusercontent.com/5146825/43649434-1227d3aa-9735-11e8-9108-d1f4946c7ad9.jpg)
![screen shot 2018-08-03 at 15 50 27](https://user-images.githubusercontent.com/5146825/43649439-141bbfa0-9735-11e8-9f5c-ecbfcf74d368.jpg)
![screen shot 2018-08-03 at 15 50 58](https://user-images.githubusercontent.com/5146825/43649441-15be51d8-9735-11e8-85e4-ba510315d78f.jpg)
This is more logos than anticipated, do we really need all of these in the footer? If so, be aware that I may not be able to fit them all on one line, and certainly won't for smaller screens.

**Comment by andyError** [comment]
We could:
- Just have the 3(?) key ones in the footer
- Have the rest in a partners block, near the footer on the homepage OR…
- Just have the remainder on a partners page somewhere on the site.

**Comment by edtjones** [comment]
@selrashidi @Forester1 can we have a steer on this please?

**Comment by martincf** [comment]
HI @selrashidi Can you give us an answer on @andyError proposal, please?

**Comment by edtjones** [comment]
@andyError @martincf is this done?

**Comment by andyError** [comment]
I've removed the School of Advanced Study logo. Still need a page of logos.
