### ISSUE TITLE
Map: close window x icon not prominent enough

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#188]
> The X to click out of the layers selection page is not very prominent. Need to be more prominent

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by andyError** [comment]
You should also be able to click anywhere in the black to close (as per the protoype). Can you make this happen @phendrick?

**Comment by andyError** [comment]
Closing, and replacing with new ticket.

**Comment by selrashidi** [comment]
Thanks - this got translated into git hub somewhat differently than what we really meant, which is that it isn't immediately obvious to users that the layer that they have switched on is actually on. (and a Close button doesn't really indicate that Layers are on).


Best wishes


Seif




________________________________

**Comment by andyError** [comment]
OK thanks, I've created a separate ticket for that, for clarity: https://github.com/layersoflondon/application/issues/399
