### ISSUE TITLE
Map: Add the alpha site satellite view layer

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#189]
[This issue has gone off the original topic]

**Comment by Forester1** [comment]
Can the satellite view be added to https://beta.layersoflondon.org/map/layers, which we have on the alpha site

**Comment by edtjones** [comment]
I'll add it, but there's a licencing issue with this which we should discuss.

**Comment by Forester1** [comment]
Ok thanks Ed. If it's urgent or breaking licence T&C can you let us know asap. Otherwise we can discuss on the weekly call
@selrashidi

**Comment by edtjones** [comment]
It's not, let's discuss tomorrow. I have used a different tileset without the issues, but the resolution is lower. See if you think it's ok.

**Comment by Forester1** [comment]
Thanks Ed, We can discuss details and options for this on the project call tomorrow.

**Comment by Forester1** [comment]
Feedback on beta:
Satellite layer is not very usable at this resolution, can we find another? If no alternatives available, can the zoom be limited before it completely pixelates?

**Comment by andyError** [comment]
@edtjones Any idea how to move forward on this?
