### ISSUE TITLE
Map: Obvious 'Go' button needed on Layers Picker

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#190]
> Once the Layer(s) have been selected a Go to map button should be at the end of the layer selection process. 

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by Forester1** [comment]
Feedback on Beta:
The X to click out of the layers selection page is not very prominent or intuitive. Needs to be more prominent
Once a layer(s) has been selected the map should be zoomed to this layer(s) when the map view appears. 
Once the Layer(s) have been selected a Go to map button should be at the end of the layer selection process.
