### ISSUE TITLE
Map: Layer tool panel, sliders hit area too small

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#192]
> LThe grab function to change opacity needs adjusting a bit – it only works if you 'grab' it in the right way, ie with the hand squarely on top – could be a bit less precise.

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by andyError** [comment]
Related to:
https://github.com/layersoflondon/application/issues/420
https://github.com/layersoflondon/application/issues/231
