### ISSUE TITLE
Map: Add Record – location address

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#194]
> the record gives the modern location where the map was clicked. In many parts of London modern addresses bear no relation to what the place/location was in a different period. So the 'address' of a church actually depends on where you exactly click on the map, so can be misleading.
Remove address from the record completely. Leave the X, Y coordinates. 

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by edtjones** [comment]
We do a reverse geocode lookup to make sure that we can search on the modern name of a place. Is that not required?

**Comment by Forester1** [comment]
Will this impact upon things like the elastic search function @edtjones ?

The key thing that is required is for the modern address not to appear on the record as it was considered misleading as the addresses were dependent on the placing of the pins. 

@selrashidi
