### ISSUE TITLE
Map: records without images

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#196]
> If record has no media associated with it, replace the media with an image of the map view location.

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by andyError** [comment]
I don't think this solution is necessary. Text-only records look good as they are, and the notion of layering maps over each other in the interface sounds like the wrong approach.

**Comment by selrashidi** [comment]
Could we show the map with the pin (rather than the blank image?)


Seif



________________________________
