### ISSUE TITLE
EJ: contact LSE re: Booth Map

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#2]
LSE are willing to work with LOL concerning the Booth Map. Their requirements are technical so, can you speak to them to help get things moving. Their main contact is retiring in March and is eager to see progress before he does (otherwise it may fall by the wayside).

**Comment by edtjones** [comment]
@selrashidi who should I be contacting?

**Comment by martincf** [comment]
LSE were contacted 17 Apr 2018 by @edtjones with costs etc.
