### ISSUE TITLE
What happens if a user removes a pin of their own which is in someone else's collection?

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#2]
Should we warn? Leave? Delete anyway? Let the other person/people know?

**Comment by andyError** [comment]
I was under the impression you could only add your own pins to your own collections - at least for now.

**Comment by edtjones** [comment]
I think that's fine, but is that the same for group collections? They will have users' pins.

**Comment by edtjones** [comment]
SOunds fine.
