### ISSUE TITLE
Map: Pick multiple eras in search

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#204]
> Search: it is essential that people can choose more than one era For example, Roman and Saxon

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by andyError** [comment]
There's a bit of a problem with  this, in that these era buttons are a way of prepopulating and end date and a start date. So the system would only accommodate multiple eras if they are contiguous.

You could set a from and to _era_ but that seems to increase the complexity - whereas this thing is supposed to provide a handy shortcut.

I'll discuss with Martin.
