### ISSUE TITLE
Map: searching for collections

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#206]
> Search: A collection search is required that allows users to select a collection and see them displayed on a map

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by edtjones** [comment]
More clarity needed. Do we need to add a 'only search collections' option on the search form?

**Comment by selrashidi** [comment]
We discussed it and we think that while we need a list of collections, we don't necessarily think that we need to be able to search "all collections" as distinct from "all records".  One thing that we think would be useful though would be able to search within a collection that the user is looking at.

**Comment by andyError** [comment]
Going to close this an open a new ticket for that last point.
