### ISSUE TITLE
Map: records ordering

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#208]
>...They are wondering how the groups of entries are ordered when you see them on screen. For example, if you search for ' conscientious objector' you get a number of records, but these are not alphabetical. Perhaps they should be?  

[From feedback doc: LoL_Beta_Review_v0.2]

**Comment by Forester1** [comment]
Thanks @edtjones . I'll ensure the rest of the team are aware of this weighting for record searching and prioritisation. This ticket can be closed
