### ISSUE TITLE
Can you create a collection when you are on the Add Record Page?

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#210]
Assuming I want to add a record and when I get to the add record page, decide that what I am actually going to do is create a collection. Can I get to the 'Create Collection' option easily?

**Comment by Forester1** [comment]
Currently no "New/Create Collection" option is appearing on the collection drop-down. See attached image. This needs to be added as an option
![image](https://user-images.githubusercontent.com/6515338/43264438-10eee3a0-90de-11e8-892d-e03aac7c884d.png) @edtjones

**Comment by andyError** [comment]
Creating a collection is a operation with some complexity (adding description, setting permissions etc.) I see how a shortcut might feel handy here, but I think in practice we'd be creating a confusing user experience by mashing the Create Collection functionality into the Add Record form. It's not perfect as it is, but it is sensible.
