### ISSUE TITLE
Ordnance Survey Five-foot to the mile (1893-1896) displaying blanks

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#212]
The Ordnance Survey Five-foot to the mile (1893-1896) are displaying significant blank tiles depending on the zoom level of the map. See image below. Can this be resolved to ensure only valid map tiles are displayed? 
![image](https://user-images.githubusercontent.com/6515338/43275635-4033761e-90fa-11e8-8a09-468493b718d4.png)

**Comment by edtjones** [comment]
Possibly not. All we do is use NLS tiles from the klokan server. Can you ask them?

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by Forester1** [comment]
Will do. Thanks

**Comment by edtjones** [comment]
Closing this - Klokan say the layer would need re-rendering. Feel free to reopen if you want to use to chase up NLS @Forester1
