### ISSUE TITLE
can't edit location of pins

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#230]

**Comment by martincf** [comment]
Duplicate of #282

**Comment by amytodd** [comment]
Has this been resolved?

Thanks
Amy Todd
Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)
The Centre for Metropolitan History,
The Institute of Historical Research,
Senate House, London WC1E 7HU
t: 02078628765
e: amy.todd@sas.ac.uk
Twitter: @LayersofLondon
________________________________

**Comment by edtjones** [comment]
@amytodd no, but this ticket is a dupe of #282
