### ISSUE TITLE
Map: Can we create 'map state' URLs?

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#237]
A suggestion from our meeting with Mapping for Change last week was to have an option to generate a URL for how the map looks at any one point in time, so enabling people to bookmark and/or share links to particular map views, eg. zoomed in on a particular map layer, or with a particular collection or record showing etc. This would be a major shortcut for people, and be great on social media. Currently we can share URLs to collections/records, but those don't replicate the map state as a whole.

**Comment by Forester1** [comment]
Feedback on beta:
Several people have asked about it as a shortcut to prevent having to re-select layers, collections, get the zoom right etc

**Comment by edtjones** [comment]
I love this idea. Will have to be after launch; @phendrick and I have some thinking to do on how best to serialise the current state.

**Comment by mpdavies** [comment]
Sure, yes it can wait but it would be really great to do!
