### ISSUE TITLE
Google Search Console meta tag

### ISSUE THREAD

**Issue by chrisunitt-xx** [layersoflondon/application#239]
To go in the `<head>`

`<meta name="google-site-verification" content="m_ZuB3ge5O49-fYiD6eMMdC_w3dAWQgE5l0Aa6XEfrE" />`

**Comment by edtjones** [comment]
@chrisunitt-xx can we do it with dns instead? it would be more robust not to have to put stuff like this in code if that's ok.

**Comment by chrisunitt-xx** [comment]
Absolutely. In which case it says to add this as a TXT record…

google-site-verification=wvkWWvGHkptFp9Kri8Ehsk5L9CLeMSM3dSRmF0O6k_E
