### ISSUE TITLE
Can you make the sub menu bigger on this page to fit everythign?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#240]
https://beta.layersoflondon.org/learning

**Comment by edtjones** [comment]
@amytodd We'll adjust the design to accommodate more, but this is a different arrangement of pages from what we discussed / agreed in the sitemap. If you really need more that's fine, but it feels maybe like there are too many pages and not enough content on each?

https://erroragency.slickplan.com/nduczfjd is the sitemap.

**Comment by edtjones** [comment]
Now resolved
