### ISSUE TITLE
Site: Unexplained <p> tag at start of content area

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#245]

**Comment by andyError** [comment]
![screen shot 2018-08-09 at 12 44 47](https://user-images.githubusercontent.com/5146825/43896860-2e53b016-9bd2-11e8-938c-40b927a3ded5.jpg)

See: https://beta.layersoflondon.org/learning

**Comment by phendrick** [comment]
a more permanent fix for this will be in rooftop-response-sanitizer (run shortcodes before creating paragraphs)

**Comment by edtjones** [comment]
Can we fix in the parse_content helper in rooftop-rails?

**Comment by edtjones** [comment]
@andyError  @phendrick can we close this?

**Comment by andyError** [comment]
Has it been fixed?

**Comment by edtjones** [comment]
think so
