### ISSUE TITLE
when is the georeferencer going to be available in the beta?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#247]

**Comment by edtjones** [comment]
Awaiting upload of the next batch of RAF images. @selrashidi?

**Comment by selrashidi** [comment]
Hendrik is supposed to be working on these today.

**Comment by edtjones** [comment]
As discussed in this week's call:

- there are no images to georeference; we need to get the 6k new images uploaded to them asap
- we have no API to get un-georeferenced images, which is a pre-requisite to building the georeferencer pages on our side

**Comment by andyError** [comment]
This is still outstanding but the tasks in this ticket have been superseded.
