### ISSUE TITLE
Feedback on beta: Home page

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#250]
Add link to Advanced Search under the main search box

Need ability for administrators to control collection(s) display on front page

administrative options to change to most popular and most viewed and manual highlight

**Comment by martincf** [comment]
1. Adv Search link will be added back when the function is working.
2. Collections on homepage will be controlled via the CMS
3. Highlights will be controlled via the CMS

**Comment by andyError** [comment]
I think this is pretty much taken care of.
