### ISSUE TITLE
Feedback on beta: Add Video

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#253]
Add media & documents
Youtube URL Not working
How do we add a video/audio file?

**Comment by edtjones** [comment]
Work on the record form is happening this week and includes the youtube video URL. Audio files can be dragged in. There is a plan for video files, but it won't be for launch - the implication is that we'll need to find a way to store / transcode for different devices / etc. The plan will probably be to upload them to youtube through their API.
