### ISSUE TITLE
Feedback on beta: Draft Record

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#255]
When returning to a draft record through the Edit function cannot see any obvious way to publish a record. See Image.  

Can we have a way to upload files that is not drag and drop as well, like an upload button from PC/Google Drive/Network location, for people that aren't able to drag and drop

![image](https://user-images.githubusercontent.com/6515338/43912047-0969fe50-9bf9-11e8-93d4-bf4b80c71176.png)

**Comment by Forester1** [comment]
Feedback on beta:
_Add media & documents_
Have to drag and drop media rather than click and upload. 

Title, caption and credit not working. Will not accept text when attempting to create a record and add a pin in one attempt.

**Comment by edtjones** [comment]
Resolved in eff1655  and 6a01a4c although there is a bit more polishing to do
