### ISSUE TITLE
Feedback on beta: Collections

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#257]
My collections and the collections created by my team are not appearing in my user profile. See Image.
 
![image](https://user-images.githubusercontent.com/6515338/43912228-9368233e-9bf9-11e8-8cf5-4bd780bd089c.png)

**Comment by Forester1** [comment]
Feedback on beta: Collections
Need ability to add collection image to represent collection in tiles

Need ability to turn on /off collection on the map through tick boxes similar to how the layers function operates in Layer Tools)

Where are all the collections displayed? In the alpha we had a list of all of them; in the beta many are undiscoverable

There is an edit button for a collection I created but it does not work

**Comment by edtjones** [comment]
Can't repeat this. Think it's solved in some recent work on collections.
