### ISSUE TITLE
Collection - read and write state should be handled in Pundit policy

### ISSUE THREAD

**Issue by ghost** [layersoflondon/application#26]

**Comment by martincf** [comment]
@edtjones Not sure what this issue is so setting to High Priority so you can close or otherwise.

**Comment by edtjones** [comment]
Not a security concern but the code is a bit funky. Making low priority. Relates to https://github.com/layersoflondon/application/blob/809081312e8864cdbb926a0102438864f5a6e8b7/src/app/models/collection.rb#L8
