### ISSUE TITLE
Feedback on beta: Example Search

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#263]
Conducted a search for the word Senate. See Image of Example search
Shows 2 records (No mention of the Collection I created called Senate House. I am logged into my user account on the website)
![image](https://user-images.githubusercontent.com/6515338/43913021-ccbf8c24-9bfb-11e8-9fbc-8e413b5cfe0d.png)

Click on one of the records (https://beta.layersoflondon.org/map/records/1439) and it successfully brings me to the record. 
Click on see on map and it returns Image below
![image](https://user-images.githubusercontent.com/6515338/43913058-f11edf7a-9bfb-11e8-882d-74270f997110.png)

The pin is a darker shade but it is not obvious where the record is and the map is zoomed out. The page also displays all of the records and collections for the zoomed out area which is unexpected as the function the user clicked for the individual record is _See on map_.

**Comment by martincf** [comment]
Action here is to:

1. zoom closer to the map pin when a user clicks on 'Show on map' within a record
2. make the design of the highlight map pin more obvious

**Comment by edtjones** [comment]
zoom in is done.
