### ISSUE TITLE
Feedback on beta: Other

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#264]
**Key user community feedback**
1. The ability for multiple users to log in using the same username and password (at the same time). Would this be possible?
2. Can people contact the curator of a collection when they are on the page of that collection?
3. Can a pin that wasn't part of a collection, be added to somebody else's collection (if the original author agrees)?
4. Beta testing 'read more' displays wrong email. Needs changing to: layersoflondon@london.ac.uk

**Comment by edtjones** [comment]
What's the use-case for (1) which is not covered by teams, @Forester1 ? Multiple people logging in with the same credentials is terrible security practice and we should be discouraging it at every turn (not to mention it stops any notion of attribution / leaderboards on georeferencer / contact this user / etc etc)

**Comment by edtjones** [comment]
Re 2: yes, we have plans in the wireframes for someone to choose to be contactable. It'll be through a form, rather than sharing the email address of the user.

Re 3: yes, and without permission in fact.

**Comment by andyError** [comment]
I don't think there's any actions here.
