### ISSUE TITLE
Map: Add media and documents UX improvements

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#266]
I could do with working through some improvements to this section with Paul.

![screen shot 2018-08-09 at 18 09 52](https://user-images.githubusercontent.com/5146825/43914341-8e7884e4-9bff-11e8-9686-d3b0680d5ca3.jpg)

- Upload button and YT URL fields need to work.
- The dotted outline images should appear as a full width block, with 'Your image will appear here, you can drag them in too' until there are > 0 images.
- The bottom box should only appear once there is an image uploaded or url added.

**Comment by andyError** [comment]
Also, when there are image thumbnails there, we need to highlight the one that has been clicked on, so that users know which image they are editing the title/credit/caption for.

**Comment by andyError** [comment]
Ok, this is all done except:

The bottom box should only appear once there is an image uploaded or url added.

**Comment by edtjones** [comment]
resolved in 1.0-beta21
