### ISSUE TITLE
Map: Add record media picker images need selected state

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#270]
We need .is-selected on the <li> of the clicked image.

![screen shot 2018-08-09 at 20 45 25](https://user-images.githubusercontent.com/5146825/43921960-3611734a-9c15-11e8-9639-9ebb0524651e.jpg)

**Comment by phendrick** [comment]
resolved in d41f80174ad6ceb1d02c50e0aa5791f8d7f52b79
