### ISSUE TITLE
Layer picker: Need to have further info popover for all layers

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#271]
This is essential as it needs to include an acknowledgement of the source of each layer and a link to their website. (plus any contextual information)

**Comment by martincf** [comment]
The Layers pages are post-launch.

**Comment by edtjones** [comment]
Let's create content-managed pages for now and link them in the description @amytodd @selrashidi

**Comment by andyError** [comment]
Now we're post-launch, we need to revisit this.

**Comment by andyError** [comment]
See wireframes linked here: https://github.com/layersoflondon/application/issues/138

**Comment by andyError** [comment]
Should be able to include video: These could set a good prototype for other contextual information and how it sits within the website. (I mentioned this in an email but thought it best to move it here).

https://www.youtube.com/watch?v=xa4CmqfakjQ
https://www.youtube.com/watch?v=OEnUNkH7HZw

https://www.youtube.com/watch?v=clKxrDza1d8

https://www.youtube.com/watch?v=i__1yngZ_-8

https://www.youtube.com/watch?v=Udpmro3UnkU

See: https://github.com/layersoflondon/application/issues/44
