### ISSUE TITLE
Schools and young people pages need better CTA's/previews for resource downloads

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#272]

**Comment by edtjones** [comment]
@amytodd we discussed yesterday just having a link in the body of the page to the pdf. Are you ok with that solution?

**Comment by martincf** [comment]
Not sure users need a PDF viewer anymore. Is this a requirement for Windows users?

**Comment by amytodd** [comment]
It is more from a design point that it would be nice to come to the page and be able to preview the resource/have a screenshot rather than just a hyperlink to where you download the PDF resource?

**Comment by amytodd** [comment]
Happy with it pre-launch but would it be possible to have something that looks nicer in the long run/ or just the ability to add some pictures to the page if not?
