### ISSUE TITLE
can we have a list of collections in the left hand tray

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#275]

**Comment by edtjones** [comment]
@amytodd we think this might be better as a toggle in search - "show only collections" - does this fit your use-case?

**Comment by amytodd** [comment]
Yep that works for me, thanks

Amy Todd
Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)
The Centre for Metropolitan History,
The Institute of Historical Research,
Senate House, London WC1E 7HU
t: 02078628765
e: amy.todd@sas.ac.uk
Twitter: @LayersofLondon
________________________________
