### ISSUE TITLE
profile picture on account; where does this get displayed?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#278]

**Comment by andyError** [comment]
I don't think it's working yet, but when it is you'll see it on Your profile > Account details like so:

![screen shot 2018-08-10 at 16 51 44](https://user-images.githubusercontent.com/5146825/43967972-b6589242-9cbd-11e8-8c38-76356c8e1c6e.jpg)

…and when users click your name and see all records by you:

![screen shot 2018-08-10 at 16 52 52](https://user-images.githubusercontent.com/5146825/43968042-e5fb4ee0-9cbd-11e8-9a85-0f33fc625596.jpg)

That's it.
