### ISSUE TITLE
How does it work when you okay people contacting you; are they able to email? How does this work?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#279]

**Comment by andyError** [comment]
Even if people agree to be contacted, their email will not be shared. There will be a **Contact user** button which pops up a message form. Once this is filled and submitted, it will be sent by the system to the user's email address.

**Comment by andyError** [comment]
Yes, there will be a button on records.

**Comment by andyError** [comment]
I'll make a new issue so it's logged.

**Comment by amytodd** [comment]
when is this happening>?
