### ISSUE TITLE
Map: Need a way to edit record location

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#282]
Under the title, there should always be the record's place in text, looking like this

![screen shot 2018-08-10 at 16 29 46](https://user-images.githubusercontent.com/5146825/43966873-ed5f1426-9cba-11e8-9986-89bfc0540dfe.jpg)
:

At the end of this text, we should have an 'Edit' link, which should take you back to the map, where you can drop/redrop a pin.

**Comment by edtjones** [comment]
Resolved in 1.0-beta20 - now clickable map on record form
