### ISSUE TITLE
"Care of Historic Collections" Tab

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#285]
In our HLF grant proposal we mentioned a section to encourage people to take care of their own collections of photos etc, and provide some guidance. Could we add an icon to the left hand side panel?

(We thought about putting it under HELP but felt it would be too discrete), or on the page with the historic Layers), but feel that for the sake of prominence, having it on the left might be best.

**Comment by martincf** [comment]
Hi Seif. We don't think having this prominently on the map section is useful. It'll unnecessary clutter the left hand menu, and be somewhat out of context. It feels like the correct approach would be to write a blog post, also have a help article; and then make sure it's well highlighted on Facebook/Twitter etc to draw attention to both articles. We could also highlight it on the homepage.
