### ISSUE TITLE
Bug: Trouble assigning Alpha Site records to a collection

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#286]
Apparently, this does not currently work

**Comment by edtjones** [comment]
More info needed please. What record? What Error? Doesn’t work how?

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by selrashidi** [comment]
John Hinshelwood is the one who mentioned it. I will ask him and get back to you

**Comment by edtjones** [comment]
We have exchanged emails on this; will re-read and raise any issues.

**Comment by martincf** [comment]
John's issues are concerned with getting a record or records into a collection. He needs to assign 97 conscientious objector records into the 'First World Ware Conscientious Objection' collection. The collection shows, but has zero records associated. John can't assign the records from the edit menu, to this collection.

**Comment by andyError** [comment]
Was this sorted @edtjones @martincf ?
