### ISSUE TITLE
Search: Introduce themes taxonomy

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#287]
These are the LMA themes, which at some point we said we would use as a taxonomy

1. Housing London
2. Healing London/Welfare for London
3. Educating London
4. Transporting London
5. Protecting and Rescuing London (Fire services, War records etc)
6. Public Buildings and and Religious Institutions
7. Entertaining London
8. Commercial London
9. Open Spaces
10. Controlling London.

Cross cutting: London Communities

**Comment by mpdavies** [comment]
We might want to leave the word 'London' off these, ie Housing, Education, Transport etc. And we might need some explanation, eg. that Controlling means government police etc. Entertainment includes sport etc.
