### ISSUE TITLE
can you please delete the addresses that display on pins? priority - have a partner waiting to use this but doesn't want to input records until this is sorted

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#288]

**Comment by andyError** [comment]
Could someone please clarify what addresses this is referring to, please?

**Comment by selrashidi** [comment]
Dear Andy,


When you come to add a record, an address appears (This address does not appear on the record itself, simply on the record form, but I think some people find it confusing as in some cases street addresses have changed and so it gives them something to fuss about).


Seif





________________________________

**Comment by andyError** [comment]
Thanks Seif - we'll just use coordinates then.
