### ISSUE TITLE
We need help if we are supposed to be using different templates for different pages if it has different designs/functionality etc because we don't know what these templates do/look like

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#293]

**Comment by mpdavies** [comment]
Which pages are you thinking of @amytodd ?

**Comment by amytodd** [comment]
![image](https://user-images.githubusercontent.com/35807842/44457443-1efbe880-a5fb-11e8-8c42-8d48cae9edcc.png)

So here - I don't know which of these templates to use/what they look like/what functionality they have? Atm I am just using default template

**Comment by edtjones** [comment]
@andyerror can you elucidate?
