### ISSUE TITLE
when will audio be ready and how will this be added to records, via soundcloud?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#294]

**Comment by edtjones** [comment]
If you drag an audio file into the attachments it should work ok. We decided against soundcloud just to reduce the number of external dependencies. Let us know on this ticket if there are issues. 

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by edtjones** [comment]
@amytodd closing this ticket - drag / add audio files to a record and there'll be a player when you view the record.
