### ISSUE TITLE
Map: Need way to reorder active layers

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#299]
is it possible to shuffle the order of map layers when using the layer tools on the map view?

**Comment by edtjones** [comment]
Yeah you are supposed to be able to drag / drop in the layer tools. I think it’s buggy. 

Nb there’s a whole load of work on Layers to do, but not for sept 21




--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by andyError** [comment]
Possible useful feedback on beta:

Layer tools box: The grab function to change opacity needs adjusting a bit – it only works if you 'grab' it in the right way, ie with the hand squarely on top – could be a bit less precise

After selecting layers and viewing the map, if wanting to select new layers with Choose new layers, the website is crashing each time

Would be good to be able to de-select layers from the Tools box
