### ISSUE TITLE
is there a way to make it easier when using the map layers to find the different maps; maybe ti can revert to where that map is (ie tudor map only displays on a small part of the map)

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#300]

**Comment by edtjones** [comment]
If we zoomed to the extent of the layer you’ve chosen would that solve this?

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by andyError** [comment]
Closing, dupe of: https://github.com/layersoflondon/application/issues/399
