### ISSUE TITLE
Map: Sort out missing placeholder images on map popovers

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#303]
Here:

![screen shot 2018-08-28 at 11 01 47](https://user-images.githubusercontent.com/5146825/44716300-d2f4ec00-aab1-11e8-8325-81b40860dbc7.jpg)

**Comment by edtjones** [comment]
images now showing, but @andyError needs to adjust the FED slightly for the wide cards

**Comment by andyError** [comment]
Done.
