### ISSUE TITLE
Collection edit button

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#308]
There is an edit button for a collection I created but it does not work

**Comment by andyError** [comment]
![screen shot 2018-08-29 at 12 02 45](https://user-images.githubusercontent.com/5146825/44783811-78c45b80-ab83-11e8-8182-77ea89aabef1.jpg)

The little yellow one on the right there ^

**Comment by martincf** [comment]
Yes, that one. Doesn't work.

**Comment by edtjones** [comment]
Resolved in f5f6ecc
