### ISSUE TITLE
Fix up the map state on page load

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#31]
When the page loads we should display:

* All the overlays
* all the pins (in bounds? that'll need an ajax call - you decide if it's worth it @foxpaul )
* no search results box
* focus on the search box

**Comment by edtjones** [comment]
@foxpaul I've generally done template-specific stuff in the PagesController slightly differently which encapsulates things a bit better IMO:

- add a mixin called something sensible: `MapContent` or something
- add a before_action in there, and the method to do the getting.

Here's an example from another project:

```
module HireTypeCollection
  extend ActiveSupport::Concern

  included do
    before_action :get_hire_types, only: :show, if: -> {@page.template.present? && @page.template.underscore == "spaces_list"}
    decorates_assigned :hire_types, with: HireTypeDecorator
  end

  private
  def get_hire_types
    @hire_types = HireType.ordered
  end
end
```

**Comment by foxpaul** [comment]
The defaults are now: 

Search results are now 'compact'. 
Overlays menu is expanded. 
Search box is focused. 

We're still just showing the Pin.latest notes on page load (to match what we're rendering on the homepage).
