### ISSUE TITLE
Add Record: Add record title and description prompts

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#310]
Could we have some text in the title and description box as examples or prompts (as we do in Credits and Attribution)?

**Comment by andyError** [comment]
From Hendrik:

Title: Can we add in an example title? For example "Trebor sweet factory on Smith Street"

Description: Can we add in an example Description or example descriptions instructions? - Can we insert a basic character limit here (say 10-25 characters) to encourage users to add some more detailed content
