### ISSUE TITLE
Tray context, titles and meta: For Search, Collection, Team, Creator etc.

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#314]
When you click on a record; it isn't clear if it is part of a collection but there is now the ability to find the contributors other work which is a new kind of collection we haven't discussed before

Can’t tell if a record is part of a collection. Needs to say so and you need to be able to see the rest of the collection.

**Comment by martincf** [comment]
We need to include the collection name near to or part of the 'Showing n records' text. For example, 'Showing 28 records in the Me Too collection' or 'Showing 28 records created by Josephine Jobbins'.

**Comment by andyError** [comment]
From the wireframes:
Default:
![screen shot 2018-08-30 at 11 23 32](https://user-images.githubusercontent.com/5146825/44848691-a5de4000-ac4f-11e8-9af9-9bc8cd2a7b1f.jpg)
Collections, Team, Creator states:
![screen shot 2018-08-30 at 11 23 16](https://user-images.githubusercontent.com/5146825/44848696-a8d93080-ac4f-11e8-9d4c-eace46d3ec4b.jpg)
Search:
![screen shot 2018-08-30 at 12 25 17](https://user-images.githubusercontent.com/5146825/44848729-c908ef80-ac4f-11e8-92fe-6b51b7db3a7b.jpg)
Search title permutations:
![screen shot 2018-08-30 at 12 26 43](https://user-images.githubusercontent.com/5146825/44848783-fb1a5180-ac4f-11e8-9ddf-4e0fdc627584.jpg)

**Comment by edtjones** [comment]
Everything but team is done
