### ISSUE TITLE
Map: Missing delete button on draft records

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#315]
Doesn't look like you can currently delete a draft record, though can can delete a published one:

Editing draft record, button is missing:
![screen shot 2018-08-29 at 12 22 24](https://user-images.githubusercontent.com/5146825/44784626-34868a80-ab86-11e8-986e-a5e57c96a8c2.jpg)

Editing published record, button is present:
![screen shot 2018-08-29 at 12 22 55](https://user-images.githubusercontent.com/5146825/44784648-4831f100-ab86-11e8-9d9c-0fa20b3418dd.jpg)

**Comment by edtjones** [comment]
Resolved in 6622c54
