### ISSUE TITLE
when are we going to have the ability to turn off records?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#319]

**Comment by edtjones** [comment]
Now; @selrashidi can set you up an admin account

**Comment by amytodd** [comment]
Sorry to clarify, can all users do this?

Amy Todd
Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)
The Centre for Metropolitan History,
The Institute of Historical Research,
Senate House, London WC1E 7HU
t: 02078628765
e: amy.todd@sas.ac.uk
Twitter: @LayersofLondon
________________________________

**Comment by edtjones** [comment]
Users can turn off their own records by setting them to draft and then deleting. Admins can delete any records. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by amytodd** [comment]
Sorry to be unclear, the enquiry was about the records appearing on the map and if there is going to be the ability to turn them on and off (so you can see the map layers clearly) thanks

Amy Todd
Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)
The Centre for Metropolitan History,
The Institute of Historical Research,
Senate House, London WC1E 7HU
t: 02078628765
e: amy.todd@sas.ac.uk
Twitter: @LayersofLondon
________________________________
