### ISSUE TITLE
Add opacity slider per overlay

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#32]
On the overlay results container we need to have an opacity slider per layer. Ideally, we should only show the slider if the overlay is switched on.
![screen shot 2016-12-08 at 21 17 43](https://cloud.githubusercontent.com/assets/4377783/21028179/e0cf0e1a-bd8b-11e6-8062-0a753516000e.png)

**Comment by foxpaul** [comment]
resolved in d1b3167900537e273220975f4e005be85cf628c0
