### ISSUE TITLE
Edit record: Error messages

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#325]
I couldn't save a record, because I'd had refreshed while editing it and it had lost it's 'place'. Needs some error messaging to help users get round issues like this.

**Comment by andyError** [comment]
Also date is needed but this is not mentioned anywhere, and you get no error message.

**Comment by edtjones** [comment]
Resolved in 1.0-beta20. Validation messages now show what is required and what you have to do before you can publish.
