### ISSUE TITLE
View record: Media gallery thumbs need to scroll

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#326]
![screen shot 2018-08-30 at 15 34 31](https://user-images.githubusercontent.com/5146825/44858603-4b9ea880-ac6a-11e8-9f29-d8b3df70accf.jpg)
These red arrow boxes need to scroll the thumbs left and right.

**Comment by edtjones** [comment]
see https://beta.layersoflondon.org/map/records/1513 for an example
