### ISSUE TITLE
View record: If a record only has one image, it shouldn't show as the hero and as a thumbnail on the right

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#331]
![screen shot 2018-08-30 at 15 56 02](https://user-images.githubusercontent.com/5146825/44860072-60c90680-ac6d-11e8-9dd6-0c7a5b6bda0d.jpg)

No need for the thumbnail on the right.

**Comment by edtjones** [comment]
shouldn't we force the view to expanded in this case @andyError ?
