### ISSUE TITLE
need to change the order of pins in a collection; how?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#334]
https://beta.layersoflondon.org/map/collections/79

**Comment by edtjones** [comment]
@amytodd is this related to the walking tours? The notion of order of records in a collection is something we'll add after launch

**Comment by amytodd** [comment]
No – for example take the LJS collection. Records show in a collection according to which record is newest so by ordering of records as 1,2,3 doesn’t display in numerical order because I didn’t add the records in that order.

Thanks

**Comment by edtjones** [comment]
This requires us to have some notion of order on records in a collection, which there currently isn't. Would you like us to order alphanumerically for now, so 1 comes before 2?

**Comment by amytodd** [comment]
Yes please that would be great


Amy Todd

Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)

The Centre for Metropolitan History,

The Institute of Historical Research,

Senate House, London WC1E 7HU

t: 02078628765
e: amy.todd@sas.ac.uk

Twitter: @LayersofLondon

________________________________

**Comment by edtjones** [comment]
Have ordered lexicographically for now (i.e. 1,2,3)
