### ISSUE TITLE
who can edit? members of drop down menu not working

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#338]

**Comment by martincf** [comment]
Seems fine for me. Can you give more details, please?

**Comment by amytodd** [comment]
![image](https://user-images.githubusercontent.com/35807842/45036857-79fafa00-b055-11e8-9819-f9ee8508ef9c.png)

It is here on the 'members of' option there seems to be an issue with member of 'section'

**Comment by edtjones** [comment]
Are you in any teams, @amytodd ?

**Comment by amytodd** [comment]
Yes Layers of London and cinde test collection


Amy Todd

Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)

The Centre for Metropolitan History,

The Institute of Historical Research,

Senate House, London WC1E 7HU

t: 02078628765
e: amy.todd@sas.ac.uk

Twitter: @LayersofLondon

________________________________

**Comment by edtjones** [comment]
I think this is resolved in some recent work we did. @amytodd can you confirm either way? (open this ticket again if necessary)
