### ISSUE TITLE
Deleting/unpublishing a record redirect

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#339]
When you are going through your records and delete/unpublish it takes you back to the map view rather than back to your list which is annoying.

**Comment by selrashidi** [comment]
![image](https://user-images.githubusercontent.com/22592196/45038226-b845e880-b058-11e8-88de-881aa3699377.png)

**Comment by selrashidi** [comment]
![image](https://user-images.githubusercontent.com/22592196/45038309-e75c5a00-b058-11e8-995f-f521402d18a8.png)

**Comment by selrashidi** [comment]
The top image shows the records in the tray when you search for Seager, the bottom image shows what you see on the map with the same search.

**Comment by andyError** [comment]
@selrashidi That is actually correct as it stands - all those records are on the same location. 

(I'm going to reopen the original issue as a new one)
