### ISSUE TITLE
Map: Layers tools box won't close once layers have been picked

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#340]
![screen shot 2018-08-31 at 11 20 24](https://user-images.githubusercontent.com/5146825/44907482-f4ebaa00-ad0f-11e8-903f-4ecfa756d052.jpg)
You should be able to hide the layer tools by clicking the title. It works before you have picked layers, but after, clicking the title tab does nothing.

**Comment by edtjones** [comment]
this was deliberate as a way to avoid a situation where users don't know how to edit / remove layers. Suggest leaving as-is @andyError

**Comment by edtjones** [comment]
Closing this; I think it's better forced open to clarify what layers you're showing.
