### ISSUE TITLE
Map: Smartphone menu should close once option clicked

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#341]
Need a bit of JS to close the smartphone menu once an option has been clicked.

![screen shot 2018-08-31 at 11 35 35](https://user-images.githubusercontent.com/5146825/44908064-01710200-ad12-11e8-8080-9f754f87164f.jpg)

Otherwise it keeps hanging around.

**Comment by edtjones** [comment]
How is this shown / hidden @andyError? Is this the same toolbar component but responsive?

**Comment by andyError** [comment]
I've written a bit of JS to show/hide when you click the hamburger, but can't quite expand it to cover all the links in React. Yes it is the same component. See tools.js - once a link is clicked, we need to remove the class 'menu-is-open' from .m-map-wrapper, and the class 'is-active' from .hamburger.

**Comment by phendrick** [comment]
This is done (in dev)
