### ISSUE TITLE
Expose search keyword on /map/search

### ISSUE THREAD

**Issue by chrisunitt-xx** [layersoflondon/application#343]
We want to know what people are searching for on the map. Possible approaches:
 - (preferred) put keyword in title as a parameter eg ?q=keyword
 - (alternative 1) push details of keyword to datalayer when search is done
 - (alternative 2) show keyword on search results page

**Comment by edtjones** [comment]
Planning on doing (preferred) AND (alternative 2) @chrisunitt-xx
