### ISSUE TITLE
Analytics: Add 404 page to /map

### ISSUE THREAD

**Issue by chrisunitt-xx** [layersoflondon/application#344]
If someone tries to access a non-existant map URL (eg https://beta.layersoflondon.org/map/ajhfajsf) the map and left-hand panel just show blank. If there was an error message or the <title> tag contained "page not found" then we could track this.

**Comment by edtjones** [comment]
@chrisunitt-xx I've done SOME of this work insofar as nonexistent _records_ at least have a 'content not found' message. See for example https://beta.layersoflondon.org/map/records/999999
