### ISSUE TITLE
Analytics: Track a successfully submitted form

### ISSUE THREAD

**Issue by chrisunitt-xx** [layersoflondon/application#345]
We want to track when a form is submitted successfully. At the moment we can only track submission attempts (which will overcount new signups).

**Comment by edtjones** [comment]
Related to #325 and #269

**Comment by edtjones** [comment]
@chrisunitt-xx what is 'successfully' in this scenario? The form updates as you go along, and you can save a draft regardless of the content, within reason. You have to fulfil some requirements to publish, though.

Maybe you can track clicking on 'publish'?

(I have just deployed a major refactor of the record form, so have a play and you'll see what I mean)

**Comment by edtjones** [comment]
@chrisunitt-xx can you let me know what you need here?

**Comment by chrisunitt-xx** [comment]
This describes what we're after https://www.simoahava.com/analytics/track-form-engagement-with-google-tag-manager/#2-why-the-form-trigger-doesn-t-always-work

We get one of these from the new user form, but not from the new record (or, I think, collection) one, so for the time being we can't track those things.
