### ISSUE TITLE
Map: Low number of records in viewport results in confusing experience when they are swapped out

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#353]
I think I have identified what is happening with records in collections. I have a feeling that with collections, any record from a particular collection can appear when you hover over the record (or you click on it) as a couple of times I have looked at a record and then found a different record there when I have gone back after a few minutes. (There definitely seems to be an element of 'choose a random record from this collection' coming in to play. I am not sure how easy this is to understand, but can explain it to you on Friday if you want.

**Comment by selrashidi** [comment]
![image](https://user-images.githubusercontent.com/22592196/45095600-5c419980-b116-11e8-9807-9b7370c6a7e0.png)

**Comment by edtjones** [comment]
From that screenshot it doesn't look like you're looking at a collection @selrashidi - you're on /map which shows you pins which are in view.

**Comment by selrashidi** [comment]
![image](https://user-images.githubusercontent.com/22592196/45095664-84c99380-b116-11e8-8e46-b783a5dd9583.png)

**Comment by selrashidi** [comment]
Glad you know what it is! (I found it puzzling)
