### ISSUE TITLE
we need to change the wording from user agreement to contributor agreement in the terms and conditions; where can we access this through CMS to change this

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#357]

**Comment by edtjones** [comment]
Where is the wording you need to change @amytodd ?

**Comment by amytodd** [comment]
https://beta.layersoflondon.org/user-agreement

**Comment by edtjones** [comment]
Here's the link to the backend @amytodd https://lol-content.rooftopcms.io/wp-admin/post.php?post=610&action=edit
