### ISSUE TITLE
Ensure attribution features are adequate for first launch

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#359]
We need to make sure all CC and copyright notices and warnings are present and clear for launch.

**Comment by edtjones** [comment]
are we happy with this @martincf @selrashidi ?

**Comment by selrashidi** [comment]
If we could link the attributions to the relevant websites, that would be ideal. If not, I think this will suffice for now.


Seif







________________________________

**Comment by andyError** [comment]
No longer relevant.
