### ISSUE TITLE
create collection button unresponsive

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#362]

**Comment by amytodd** [comment]
Now displaying this:

https://beta.layersoflondon.org/records

**Comment by edtjones** [comment]
Hi Amy

I think I fixed this. Still broken?

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by amytodd** [comment]
Hi Ed – yes its either unresponsive or you get this: https://beta.layersoflondon.org/records

Thanks
