### ISSUE TITLE
Caching issue? Guides and FAQs being deleted but still showing on front end

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#364]
test entries have been deleted in the CMA but still showing on the site

**Comment by edtjones** [comment]
Hmm weird. can I have an example please?

**Comment by amytodd** [comment]
[cid:image001.png@01D449B8.6FE66FD0]
These are deleted on the CMS but still showing

**Comment by amytodd** [comment]
![image](https://user-images.githubusercontent.com/35807842/45428640-902e3900-b699-11e8-9fe7-a11a322c8790.png)
 there isnt this question in the CMS - it has all been updated but isnt showing on the site

**Comment by amytodd** [comment]
it is the same with the user guides
