### ISSUE TITLE
legal and technical page is showing as published under help centre but isnt showing in the front end? 

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#365]
``

**Comment by martincf** [comment]
The Help Centre page doesn't have a sub-navigation. It was dependant on Guides being created, which would appear in the Help Centre (and FAQs). Did you intend on Legal & Technical being a guide? If so, recreate it in the Guides section. Alternatively, you can add it to the footer menu, as the Terms, Policy pages etc have been.

**Comment by andyError** [comment]
Sorted in the past.
