### ISSUE TITLE
Credits and attribution Highlight your text to add a link.

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#367]
what does this mean? how does this work?

**Comment by edtjones** [comment]
Maybe we need something more explanatory. Highlight the text you want to turn into a link and you'll see a popover link option.

**Comment by amytodd** [comment]
I don’t think it is clear and have had a user report it was confusing – I can understand one button doesn’t look good though

**Comment by amytodd** [comment]
Yes something like that would be helpful thanks

**Comment by andyError** [comment]
Done.
