### ISSUE TITLE
Admin: Issue with editing records

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#368]
![image](https://user-images.githubusercontent.com/35807842/45353531-f5f3c580-b5b2-11e8-8799-f7d7341aa172.png)

Front end the record displays lots of text but in the back end and also admin interface the long text is not showing. User says the text is also dissappeared when editing 

https://beta.layersoflondon.org/map/records/50

**Comment by edtjones** [comment]
What browser is being used on the website 'edit your record' screen? Want to repeat the problem if I can.
