### ISSUE TITLE
From single user account to multiple user accounts question

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#369]
If a physical team or community group move from using a single username and password for their project to using individual accounts and the Teams function, would all the users of the team still have access to the content generated under the original account?

**Comment by andyError** [comment]
_All team members can edit any of the team's assigned collections –  add pins; remove pins, but can not edit records unless the record(s) have been explicitly set by the creator to be editable by a team_

So the answer is: yes. They would need to create the team, then log in as the original single user account and set each record to be editable by the team.

BUT we haven't finished this functionality yet as far as I can tell. We'll discuss internally and get back to you.
