### ISSUE TITLE
Team permissions question

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#370]
If a member of a team puts content online that the other members of the team disagree with and want taken down, can the team take this content down?

**Comment by andyError** [comment]
From the wiki:

- All team members can edit any of the team's assigned collections –  add pins; remove pins, but can not edit records unless the record(s) have been explicitly set by the creator to be editable by a team
- When a user creates a record they can assign editor rights to a team (see above)

Can a team member remove another members collections from the team @edtjones @martincf ?
