### ISSUE TITLE
Own collections not showing up in Add Record form

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#372]
when you try to add a record in a collection the collection drop down menu isnt showing your collections; for example I am the owner of LJS test collection and I cannot add any records to this collection  as it isn't showing.

**Comment by edtjones** [comment]
Just for debugging purposes, can you tell me if it's there if you do a full page refresh?

**Comment by amytodd** [comment]
Yes it is still showing as no options;


[cid:fffff5ce-0abb-4bc1-9624-069437157464]


Amy Todd

Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)

The Centre for Metropolitan History,

The Institute of Historical Research,

Senate House, London WC1E 7HU

t: 02078628765
e: amy.todd@sas.ac.uk

Twitter: @LayersofLondon

________________________________

**Comment by edtjones** [comment]
have resolved in total rewrite of the collections picker, launching today
