### ISSUE TITLE
Add record: Compare formatting in the description box, with the finished record

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#374]
Users have reported issues with gaps in text displaying in front end when they dont appear when adding records (see Joe Strummer record)

**Comment by edtjones** [comment]
Hi Amy 

The record description? It’s got formatting. Or maybe I have misunderstood?

**Comment by amytodd** [comment]
Yes sorry maybe I am using the wrong language. User reported that there are weird gaps that come up when published. There is formatting though and maybe I should add that into user guides.
