### ISSUE TITLE
any progress on this? it is still not displaying the list of my collections

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#378]
![image](https://user-images.githubusercontent.com/35807842/45551739-bcc38b80-b826-11e8-9ee5-d4ce50be661e.png)

**Comment by edtjones** [comment]
Lots. I'm rewriting the collections stuff having investigated and found a few bugs. Hoping to have it finished and deployed (much) later today.

**Comment by edtjones** [comment]
(It'll also include 'add this record to a collection' for a record which you don't own)

**Comment by amytodd** [comment]
Thanks

**Comment by andyError** [comment]
Pretty sure this is sorted now.
