### ISSUE TITLE
Error made this menu link

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#379]
I've create an 'Error made this' image. Needs adding into the footer of the expanding left-hand menu. See example attached. 

Images (a PNG and/or SVG) are in the project folder -> Website/Error made this.

<img width="690" alt="screen shot 2018-09-14 at 16 07 14" src="https://user-images.githubusercontent.com/1022898/45559541-a8898980-b83a-11e8-8f01-eb9aa0d6d95c.png">

**Comment by andyError** [comment]
Done.
