### ISSUE TITLE
Map search results overlap +/- buttons

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#38]
Related to #37 the map search results are too long on a 13" screen and hit the zoom buttons.
![screen shot 2016-12-08 at 21 30 47](https://cloud.githubusercontent.com/assets/4377783/21028566/9dde9d58-bd8d-11e6-8bf0-4fd5852c7f26.png)

**Comment by andyError** [comment]
Shouldn't anymore, I'm jquerying a max-height onto the box on page load.
