### ISSUE TITLE
Poor quality of the modern satellite layer

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#380]
From Matthew: While I remember, is anything going to be done about the satellite image layer? It’s a bit frustrating to be able to zoom in to the 1940s map and the 1940s photos but not be able to see an image of what’s there today because the resolution of the modern satellite map is so poor…

**Comment by edtjones** [comment]
There’s a licensing issue here. The one we had on the alpha was not licenced for our use. Let’s discuss. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by selrashidi** [comment]
What options do we have?


Seif





________________________________

**Comment by edtjones** [comment]
There are tiles we can use but the licensing situation is hazy. Hard to promote that approach :-)

Alternatively there are paid solutions with free access for small volumes - eg https://developer.mapquest.com/plans

Don’t suppose any of our partners have a licence to high res aerial / satellite which we can take advantage of?
--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by selrashidi** [comment]
I will ask Chris Fleet.


Seif




________________________________

**Comment by edtjones** [comment]
Any news on this @selrashidi ?

**Comment by edtjones** [comment]
Now using the ESRI layer from https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer
