### ISSUE TITLE
Logos in the footer

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#381]
The School of Advanced Study logo should be the one attached rather than the one current one. 

Also, the link to from the IHR logo links to HLF rather than to the IHR website. Could you please change it?

![4 greyscale logo white text cmyk](https://user-images.githubusercontent.com/22592196/45681399-55af1b00-bb35-11e8-91e6-1a1c3a4e3982.png)
![6 mono logo white text cmyk](https://user-images.githubusercontent.com/22592196/45682377-08807880-bb38-11e8-929d-6d6b390a04aa.png)

**Comment by andyError** [comment]
Hi Seif, in another ticket you asked to remove the School of Advanced Study logo on account of it being included in the IHR logo - I've just done this.

**Comment by andyError** [comment]
I've fixed the link too (though not deployed yet). The footer will look like this:

![screen shot 2018-09-18 at 12 07 52](https://user-images.githubusercontent.com/5146825/45683443-901bb680-bb3b-11e8-89c3-394abd478488.jpg)

**Comment by selrashidi** [comment]
Thanks. I realised that the logos link to web pages, and thus it makes sense for the School of Advanced Study logo to be there (but with the current logo, if that's ok).


Also, I can't see the 'Error made this' bit. Have you added it?


Seif


________________________________

**Comment by andyError** [comment]
Yep, I'll put it back. Error logo is on the map currently but not on the marketing site.
![screen shot 2018-09-18 at 13 00 13](https://user-images.githubusercontent.com/5146825/45685908-cf013a80-bb42-11e8-82c9-cada54e5b513.jpg)

**Comment by andyError** [comment]
![screen shot 2018-09-18 at 13 14 08](https://user-images.githubusercontent.com/5146825/45686618-cc9fe000-bb44-11e8-9857-2d0acee0cb5c.jpg)
