### ISSUE TITLE
My new record text automatically shows in the title box; can we get rid of this? Now we have lots of 'my new record' test pins

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#385]

**Comment by edtjones** [comment]
We need *something* in there. Could be anything. This is a function of the fact that draft pins have to have a title, so we default to that. I.e. it can’t easily be blank. Any better idea about what text?

Ed

--
Error
A human-centred interaction agency

4th Floor, 86-90 Paul Street,
London, EC2A 4NE

Tel: 020 3637 5060
Mobile: 0779 187 4282
Twitter: @erroragency
http://error.agency <http://error.agency/>

**Comment by amytodd** [comment]
Maybe a question like, what do you want to call this record?
