### ISSUE TITLE
Add credits to map layers

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#386]
We need to allow for Source credits on the map layer descriptions

**Comment by selrashidi** [comment]
Ha - I was just thinking of this.


The Evening Standard plans to run an article on Thursday focusing on the 1890s and 1940s Layers. As such, do you think we could do this tomorrow?


Best wishes,


Seif




________________________________

**Comment by edtjones** [comment]
Seif can you create the pages in Rooftop which these will link to in the short term? that’ll give you somewhere to put copy. You can also add a link in the description for each layer - we’ll need to make them into links but that’s about it.

Ed

**Comment by selrashidi** [comment]
Ok, I will.

**Comment by andyError** [comment]
Kinda done, and in future will be covered by: https://github.com/layersoflondon/application/issues/271
