### ISSUE TITLE
Create collection link in toolbar is unresponsive

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#408]

**Comment by edtjones** [comment]
which one, @amytodd - and what screen were you on when you clicked it? Were you logged in or out? Browser?

**Comment by amytodd** [comment]
Chrome and logged in

Map screen

**Comment by andyError** [comment]
I can't recreate this, I assume it's working for you now, @amytodd? If it happens again, we'll need more information in order to fix. Best I can say is we'll keep an eye out for it really.

**Comment by amytodd** [comment]
It I still unresponsive – is it working for you?

I am on chrome on my desktop

**Comment by andyError** [comment]
This link in the sidebar?

![screenshot 2018-10-09 at 16 46 04](https://user-images.githubusercontent.com/5146825/46681294-d916d600-cbe2-11e8-9474-5d3a73e50fbe.jpg)

**Comment by andyError** [comment]
Strange, it seems functional in Chrome/PC here.

![virtualbox_ie11 - win10_09_10_2018_16_52_28](https://user-images.githubusercontent.com/5146825/46681753-ccdf4880-cbe3-11e8-9562-cb7a67d8412f.png)

**Comment by andyError** [comment]
Could you try something for me? In Chrome, press CTRL + SHIFT + I, to open Developer Tools. You should see various gubbins down the side (or maybe along the bottom). Then try and click the offending button again, and see if errors are displayed in the Console area of the tools. Should be somewhere like this:

![virtualbox_ie11 - win10_09_10_2018_16_54_18](https://user-images.githubusercontent.com/5146825/46681989-598a0680-cbe4-11e8-9288-fe1ef6834a0d.png)

**Comment by amytodd** [comment]
[cid:image001.png@01D45FF3.0084C5A0] Like this?

**Comment by andyError** [comment]
I can't see that for some reason. Is it a screenshot of an error? Want to try emailing it to me?

**Comment by andyError** [comment]
Could you try again @amytodd, please? Is this still not working for you?

**Comment by amytodd** [comment]
Still unresponsive

Thanks

**Comment by andyError** [comment]
Could you check the dev tools as described above? See if there's any errors, please. (I haven't received that screenshot anywhere)

**Comment by amytodd** [comment]
[cid:image001.png@01D4624A.FFB10440]

Apologies, thought I had sent it

**Comment by andyError** [comment]
That's not working for some reason - all I can see is:

![screenshot 2018-10-12 at 16 50 59](https://user-images.githubusercontent.com/5146825/46879872-0c55a100-ce3f-11e8-846c-665b1d078e60.jpg)

Might have to email it.

**Comment by amytodd** [comment]
[cid:image001.png@01D4624C.1CFB3A10]

**Comment by andyError** [comment]
Same again. It's really not working.

**Comment by martincf** [comment]
Hi Amy. Can you send through a screenshot (zip it up first) for this issue, please?
