### ISSUE TITLE
I set up a record for Charlton House recently – there seems to be a strange quirk in the date cell. When I add the date of completion, 1612, the date then changes to other years, e.g. 1610 or 11.  Frustratingly inaccurate dates!

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#409]
from user

**Comment by andyError** [comment]
The developers are aware of this, I think there's a couple of tickets pertaining to this bug, so I will bring them all together.

**Comment by andyError** [comment]
Closing as dupe of: https://github.com/layersoflondon/application/issues/443
