### ISSUE TITLE
analytics for measuring vol hours on site 

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#423]
@chrisunitt-xx

**Comment by chrisunitt-xx** [comment]
Is there any context for this one? Mostly, does this number need to be reported to someone?

As a heads-up, time on site can't be measured reliably with Google Analytics, but it can give a very rough idea.

**Comment by edtjones** [comment]
@amytodd and I previously discussed using various things as proxies for time spent - so eg half an hour creating a new record or whatever. I could report on number of records in draft and published state if that would be helpful. 

Depending on what events you are firing in GTM/GA there might be more granular proxies too, like number of times someone has interacted with a collection they created, etc.

**Comment by chrisunitt-xx** [comment]
Ok, thanks. So the first one would best be done outside of GA if it was needed. 

"number of times someone has interacted with a collection they created" hides a couple of complexities - surfacing the user id of the record/collection creator on the site so it can be picked up by GA, then adding some more accurate time-on-site logging to get round the way GA is a bit rubbish at tracking that (it doesn't record the time on the last page, although there are workarounds). It's do-able, but way outside the current scope of the work that I've been set.

**Comment by amytodd** [comment]
To clairfy; what can google analytics show us? In terms of what would we ideal is we would like data such as : new users per month/ where they are coming from/ how long they spent on site/ peak traffic times?

Then there is another element which is measuring 'volunteer time' online; which I thik is best done in a metric as mentioned by Ed; so we can agree this with the team I suppose? @selrashidi
