### ISSUE TITLE
Adding Records/Collections

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#426]
Adding Records / Collections

When creating a new record, nice to have the option to create a new collection at the same time

Record does not immediately appear within My Records. Only visible within My Profile (draft)

My Collections - Only visible with My Profile, would be nice to have a link in left hand menu

Your Records - should show Draft records

Within record view, the Edit button is at the bottom of the screen, off window rather than instantly visible

Create Collection - button stopped working during session

**Comment by amytodd** [comment]
priority

**Comment by andyError** [comment]
Amy has broken these out into individual tickets, so closing this.
