### ISSUE TITLE
Add notes for clarity on Private & Public / Published & Draft / Only I can see

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#429]
Clarity required - Private & Public / Published & Draft / Only I can see - Users may expect that private means private to them. Can include a table explaining who can see what, like Facebook

I completely appreciate that making everything public should be the standard, but there should be an option for private & unpublished (e.g. for personal history containing data specific details (place of birth))

Private Collections may be an option

**Comment by amytodd** [comment]
private collections are a thing - ignore this point
