### ISSUE TITLE
Various things we wish to remind you of  for the new site

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#43]
1. Admin Rights: We would like to make sure we have admin rights to enable us to edit pins/delete inappropriate material. 
2. Permission to publish; attribution of a source to appear in the new version of the website. It doesn't currently as you know.
3. Terms and conditions as Martin and I discussed yesterday. (A general terms and conditions on sign up and then a tick box to remind users before a pin goes live. 
4. Have you thought of an easy to use help system - for example with question marks? Do you need us to help writing the content?
5. On the Terms and Conditions, GDPR etc, one thing that does need to be included is reference to Creative Commons. All content on the site must be available under a Creative Commons CC-BY-NC licence, and so as well as confirming that they have permission from copyright holders, users would also be confirming that they are willing to share the content through such a licence. Somewhere on the site it needs to say that ‘This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License’.

Thanks

**Comment by andyError** [comment]
No longer relevant.
