### ISSUE TITLE
Modal help message needs lining up

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#43]
The modal help message needs sorting out a bit. I realise it's not really possible to make it totally generic, but it doesn't look useful at the moment.
![screen shot 2016-12-08 at 21 48 11](https://cloud.githubusercontent.com/assets/4377783/21029116/1f87dce6-bd90-11e6-9db7-006bfe79870a.png)

**Comment by andyError** [comment]
It's better now.
