### ISSUE TITLE
can we have the title first and then the date? it looks weird having the date first - priority

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#431]

**Comment by andyError** [comment]
Is this concerning the record view?

![screenshot 2018-10-11 at 12 49 02](https://user-images.githubusercontent.com/5146825/46802016-1189f180-cd54-11e8-9d72-e342402d3515.jpg)

…if so I think I disagree, it feels natural to me.

**Comment by amytodd** [comment]
I think the issue is that the date is quite large and prominent and the first thing you see? This has been reported by lots of users but happy to compromise?
