### ISSUE TITLE
when can we turn off records? - priority

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#438]

**Comment by andyError** [comment]
This can be done in admin.

**Comment by amytodd** [comment]
I meant turn off records on the map view so users can see the map layers without seeing the records

**Comment by andyError** [comment]
Most likely November, we're just going through the process of planning what's going to happen when in the post-launch sprints, so that's about as definite as I can give you today. Going to close this as dupe of: https://github.com/layersoflondon/application/issues/169
