### ISSUE TITLE
Short films to be added in conjunction with map layers

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#44]
These could set a good prototype for other contextual information and how it sits within the website.  (I mentioned this in an email but thought it best to move it here). 

https://www.youtube.com/watch?v=xa4CmqfakjQ
https://www.youtube.com/watch?v=OEnUNkH7HZw

https://www.youtube.com/watch?v=clKxrDza1d8

https://www.youtube.com/watch?v=i__1yngZ_-8

https://www.youtube.com/watch?v=Udpmro3UnkU

**Comment by martincf** [comment]
We'll work this into the Layers sublayers work.

**Comment by andyError** [comment]
Closing, covered by: https://github.com/layersoflondon/application/issues/44
