### ISSUE TITLE
Map: User issue when editing record location

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#441]
Could you also let the web people know that it seems to be impossible to adjust  the pointer once the site has been selected.  I tried to move the Camp B point from 13 to 11 Gosdstone Rd - and failed!

**Comment by andyError** [comment]
Hmm, I can't recreate this. You can click the little map to re-drop the pin - which is functional. Any idea *how* this user failed?

![screenshot 2018-10-09 at 17 14 02](https://user-images.githubusercontent.com/5146825/46682949-ce5e4000-cbe6-11e8-8673-83181ad12c8c.jpg)
