### ISSUE TITLE
Add record: Date is being updated against user's will on round trip to server

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#443]
The problem is with entering the date under 'When did this happen?'. I entered the year 1196, but every time I reopen the draft article to do some editing, the year has gone down. The first time I noticed it, the date had gone down to 1191. (The end date remains unchanged.) I've tried correcting the date, but again, each time I reopen the article the date has gone down. Do you have any idea what is going on?

**Comment by edtjones** [comment]
@amytodd we think this has something to do with the date of the computer the user is using (although it shouldn't and we need to fix it!) - can you find out what browser / version / operating system / please, and whether the user's machine is likely to have an incorrect date?

What a silly bug.

**Comment by edtjones** [comment]
(we are having problems repeating this so any info on how to repeat would be ace)

**Comment by amytodd** [comment]
Have asked the 3 users, thanks

Amy Todd
Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)
The Centre for Metropolitan History,
The Institute of Historical Research,
Senate House, London WC1E 7HU
t: 02078628765
e: amy.todd@sas.ac.uk
Twitter: @LayersofLondon
________________________________

**Comment by amytodd** [comment]
Hi Amy.

I'm using Chrome and the date/time is accurate.

**Comment by andyError** [comment]
From another user: 'I set up a record for Charlton House recently – there seems to be a strange quirk in the date cell. When I add the date of completion, 1612, the date then changes to other years, e.g. 1610 or 11. Frustratingly inaccurate dates!'

**Comment by andyError** [comment]
From an earlier ticket, which I made: 'Day field in Date picker decrements when the user focuses other fields, when the system timezone is wrong. Seem to only happen with more western timezones. Happens on Mac and PC.'

**Comment by amytodd** [comment]
Just to add it also happens when just adding the year and not day or date

**Comment by amytodd** [comment]
Yes I use Chrome. 

To describe what happens. I put a year in (1824)  then click the mouse, immediately the year decreases to 1823. I try to put the end year in (1844) and it won’t accept it, it says 1840. I try and increase it, but it won’t go up. 

In the end I actually had to put in 1825 in order for it to save 1824. And I couldn’t insert the correct end Year at all so just left it out. 
 


- user has reported this is still happening

**Comment by edtjones** [comment]
We found the source of this bug, which was related to british summer time and the beginning of the day. Resolved in c16e1ab7806500e9d3e3dfbdca356da8309834c4
