### ISSUE TITLE
Cache Bug: Clear the 'Help Centre' page cache when we get a webhook from Rooftop for guides

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#444]
https://lol-content.rooftopcms.io/wp-admin/post.php?post=994&action=edit

**Comment by edtjones** [comment]
Have manually sorted but we need to clear the help centre page cache when we get a webhook from Rooftop for guides, so leaving open.

**Comment by amytodd** [comment]
https://lol-content.rooftopcms.io/wp-admin/post.php?post=998&action=edit another too, thanks

**Comment by edtjones** [comment]
Done :)
