### ISSUE TITLE
Search Console verification

### ISSUE THREAD

**Issue by chrisunitt-xx** [layersoflondon/application#445]
This is required per domain, so now the site has moved to www.layersoflondon.com the verification needs to be done again.

Two options:

1. Move the noscript GTM snippet to immediately after the <body> tag so I can verify via GTM
2. Add the TXT record below to the DNS configuration

google-site-verification=m_ZuB3ge5O49-fYiD6eMMdC_w3dAWQgE5l0Aa6XEfrE

**Comment by edtjones** [comment]
Hi Chris

Have added another txt record but there was already one. So now there are 2. Let me know if I’ve done it wrong. My recollection was that google only verified the whole domain. 

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by chrisunitt-xx** [comment]
That's worked! You can delete the original record now if you like. I'll mark this as closed.

Not sure if it's changed, by Search Console handles different domains separately. Best practice would be to have separate SC properties for:
http://example.com/
http://www.example.com/
https://example.com/
https://www.example.com/
Plus any applicable localised versions. But that'd be ridiculous!
