### ISSUE TITLE
Adding data attributes on map markers

### ISSUE THREAD

**Issue by chrisunitt-xx** [layersoflondon/application#446]
We want to know how many people click on map markers.

At the moment I'm firing GA event tags when people click an element with a CSS class of 'leaflet-marker-icon leaflet-zoom-animated leaflet-interactive'. Which is a bit brittle. I also can't pick up which record they're clicking.

To improve this, could we add data attributes to the markers that look like this?

`data-tracking-marker="{{record name}}"`

**Comment by edtjones** [comment]
Yeah should be fine but record name isn’t unique. Does it need to be human readable? If so let’s hyphenate and add the id? Or easier would be just id if not necessary to be human readable. 

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by chrisunitt-xx** [comment]
recordname+id would be good.

This is to show up in reports, so id numbers on their own won't mean a great deal.
