### ISSUE TITLE
'Add pin' form needs to fit in the viewport

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#45]
It scrolls inelegantly on a 13" MBP. Maybe we could make it wider and have 2 cols? Or something better.
![screen shot 2016-12-08 at 21 50 21](https://cloud.githubusercontent.com/assets/4377783/21029169/5a593bc6-bd90-11e6-99cd-588b0f542e07.png)

**Comment by andyError** [comment]
Should scroll neatly within the overlay now, without busting the bodychops.
