### ISSUE TITLE
user question about collections 

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#450]
I have one question: If I have two different collections, can I put one sub-category into both collections: i.e. Eleanor Coade’s artificial stone manufactory is an integral part of the history of stone and cement industry of Lambeth/Nine Elms, but also part of a potential collection on Female Industrialists at work in Lambeth.

**Comment by andyError** [comment]
I think I'm being stupid. A record can, of course, go into multiple collections. I'm not sure what is meant by sub-category.

**Comment by amytodd** [comment]
Thanks – I didn’t know that a record could go into more than one collection so thanks for that. Will clarify the sub-category.

**Comment by andyError** [comment]
Yes, once a record is created, it can be added to as many collections as the user likes - plus any other user is able to add that same record to as many collections as they like. I'm going to pre-emptively close this, I think it's probably just terminology troubles.
