### ISSUE TITLE
user feedback

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#454]
sorry, don't know if you want feedback via twitter, but here you go:  1.   I can't get quotation (whatever that does) or indent to appear e.g. in the quotation here https://www.layersoflondon.org/map/records/2066 …  2. the rather vertical image of Furnival's Inn appears in landscape with blank space on the collection page; this is odd https://www.layersoflondon.org/map/records/2066 …  3. would be good to be able to decide the order in which things appear in the collection, rather than just alphabetical default  best wishes, Lee

**Comment by andyError** [comment]
Closing, I've creating separate tickets for 1 and 3. I can't make sense of 2.
