### ISSUE TITLE
View record: Related links showing on records, but not on Add record form

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#465]
There is still an issue with editing earlier records. For example in the record for Walter Charles Hohnrodt there is still a heading for Related Links which cannot be edited or deleted. When I spoke to Ed at the launch and drew his attention to this he said it was still to be sorted but obviously it hasn't been. Now that it is possible to add and edit Sources and Attribution the Related Links heading is unnecessary and confusing.

The only way around this at the moment is to copy the content of a record to a word document, then delete the record, then add a new record and paste in the content from the word document. I've tried this twice and it is very tedious and time consuming.
 (from user)

**Comment by andyError** [comment]
Currently, the functionality to add related links has been removed from the Add Record form - but we're still rendering Related links on records. I'm not sure why this is. We need to remove it from view or add it back to the add record form. @edtjones @phendrick any idea what direction are we heading with this?

**Comment by edtjones** [comment]
We intend to add it back into the record form
