### ISSUE TITLE
Some maps have rectangular borders 

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#472]
The Rocque 1746 map and the 1658 Faithorne map both have rectangular borders (black and white respectively), when they should just show the warped image. I'm sure the Rocque map wasn't doing that before!
Viewed in Chrome.

![image](https://user-images.githubusercontent.com/22591186/47567714-3cb13b00-d927-11e8-9f26-ff0945cba698.png)

Matthew

**Comment by edtjones** [comment]
Have liaised with Lewis who is re-tiling
