### ISSUE TITLE
cannot create collection through back end or front end

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#473]
I am in the admin and creating a collection and it wont save and doesn't display in the back or front end

**Comment by amytodd** [comment]
![image](https://user-images.githubusercontent.com/35807842/47848681-0bbd8400-ddc7-11e8-9efd-03d077a23f7b.png)
 This is what I want but it will not save

**Comment by phendrick** [comment]
Hi Amy, 
We've resolved the issue with this and added the records to that collection (https://www.layersoflondon.org/collections/141)

**Comment by amytodd** [comment]
Thanks! 😃


Amy Todd

Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)

The Centre for Metropolitan History,

The Institute of Historical Research,

Senate House, London WC1E 7HU

t: 02078628765
e: amy.todd@sas.ac.uk

Twitter: @LayersofLondon

________________________________
