### ISSUE TITLE
Change user name

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#474]
I am posting some records on behalf of others but it says I am the author; how do I change this?

**Comment by edtjones** [comment]
We can do it for you Amy - email the details privately and I'll sort. Assume the real person has an account?

(We are working on a 'log in as' function so you can do things like this as the user)

**Comment by amytodd** [comment]
Thanks - it would be easiest to get the collection part working so I can create the collection and then we can change the name I assume?


At the minute they are seperate records as I can't create a collection,


Thanks


Amy Todd

Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)

The Centre for Metropolitan History,

The Institute of Historical Research,

Senate House, London WC1E 7HU

t: 02078628765
e: amy.todd@sas.ac.uk

Twitter: @LayersofLondon

________________________________

**Comment by martincf** [comment]
Hi @amytodd is this still an issue?

**Comment by amytodd** [comment]
Can be closed

Thanks
