### ISSUE TITLE
paragraphs disappear when you change anything else on the form before publishing

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#475]
Please check you've included these in your issue:

- [ ] A title which summarises the problem or describes the desired outcome

If this is a bug or something is broken:

- [ ] A description which explains how to repeat the problem
- [ ] Information about the browser (e.g. Chrome), version (e.g. 54) and platform (e.g. Windows) where you had the problem
- [ ] A screenshot of your problem. Find out more here: https://www.take-a-screenshot.org/
- [ ] A theme label of _bug_

If this is a suggestion, question or future development idea:

- [ ] A description which explains your issue
- [ ] An appropriate theme label

**Comment by martincf** [comment]
Hi Amy... Can you let me which browser and which text box the text disappears from?

**Comment by amytodd** [comment]
Doesn’t happen anymore

Thanks
