### ISSUE TITLE
Search Variants - Street, St, Saint, St. 

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#48]
LMA asked about search variants and noted Saint at St as a good example. (Especially that St can also be used for Street).

**Comment by Forester1** [comment]
The abbreviation name finder on the openstreet wiki may be of assistance https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations

**Comment by edtjones** [comment]
There'll be a couple of ways to handle this in the ElasticSearch - synonyms for the less-obvious stuff, and stemming words (i.e. finding their common root)

**Comment by edtjones** [comment]
I think the stemming we have in ES is sufficient for now.
