### ISSUE TITLE
Enhancements to record form

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#480]
In order to improve the content Amy is putting together ten tips for writing good records. We think it would be good to feature them in the same way that you feature the text below on this form. 

Please check you've included these in your issue:

- [ ] A title which summarises the problem or describes the desired outcome

If this is a bug or something is broken:

- [ ] A description which explains how to repeat the problem
- [ ] Information about the browser (e.g. Chrome), version (e.g. 54) and platform (e.g. Windows) where you had the problem
- [ ] A screenshot of your problem. Find out more here: https://www.take-a-screenshot.org/
- [ ] A theme label of _bug_

If this is a suggestion, question or future development idea:

- [ ] A description which explains your issue
- [ ] An appropriate theme label

**Comment by edtjones** [comment]
good idea - so as the placeholder in the record WYSIWYG?
