### ISSUE TITLE
Comment feature versus report this record  Enhancement

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#481]
In the addition of new features phase in December we would like to add the comment feature in part to discourage people from contacting us every time they find a small error. It would be best if they commented "this record is too far east" rather than flagging it up with us. 

As such, we could consider renaming the 'report this record' button something more specific like
Report Offensive/Illegal Material

**Comment by edtjones** [comment]
Should comments be public?

**Comment by selrashidi** [comment]
Yes. (You could also add a 'contact this contributor' button), but I don't think that should replace the comment feature.


Seif





________________________________
