### ISSUE TITLE
Teacher's Feature  Enhancement

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#482]
We very much like the way the teachers feature works but think that it would be useful for the teachers to be able to get to it from the Learning heading as well. 

Can you think of a good way of doing this - or should Amy write some text and cut and paste it into the learning section. I don't think that the current set up of doing it from my the dashboard is the most obvious way of doing it.

**Comment by martincf** [comment]
You could create a page in the Learning section and put a link in the content (to the feature).
