### ISSUE TITLE
what if the record relates to something that exists today:  you dont want to enter an end date but how do you show this?

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#483]
Please check you've included these in your issue:

- [x] A title which summarises the problem or describes the desired outcome

If this is a bug or something is broken:

- [ ] A description which explains how to repeat the problem
- [ ] Information about the browser (e.g. Chrome), version (e.g. 54) and platform (e.g. Windows) where you had the problem
- [ ] A screenshot of your problem. Find out more here: https://www.take-a-screenshot.org/
- [ ] A theme label of _bug_

If this is a suggestion, question or future development idea:

- [ ] A description which explains your issue
- [ ] An appropriate theme label

**Comment by martincf** [comment]
Leave the end date blank.
