### ISSUE TITLE
i just tried to save a collection (kenley one) and just when i saved it it said 'server error'

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#484]
Please check you've included these in your issue:

- [ ] A title which summarises the problem or describes the desired outcome

If this is a bug or something is broken:

- [ ] A description which explains how to repeat the problem
- [ ] Information about the browser (e.g. Chrome), version (e.g. 54) and platform (e.g. Windows) where you had the problem
- [ ] A screenshot of your problem. Find out more here: https://www.take-a-screenshot.org/
- [ ] A theme label of _bug_

If this is a suggestion, question or future development idea:

- [ ] A description which explains your issue
- [ ] An appropriate theme label

**Comment by amytodd** [comment]
![image](https://user-images.githubusercontent.com/35807842/48359381-bcb00280-e694-11e8-8384-491402acc2d1.png)

**Comment by phendrick** [comment]
Hi Amy, 
trying to replicate this issue - can you tell me the steps you're taking to get the server error?

**Comment by edtjones** [comment]
This was an issue with data which we've since resolved
