### ISSUE TITLE
pins not showing the picture in preview on the map; only when you click through to the individual pin

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#488]
Using chrome, on map view, look at any record and it wont display the pictures.

- [x ] A theme label of _bug_

![image](https://user-images.githubusercontent.com/35807842/48498670-a047cd80-e82e-11e8-9f86-4da9f5f23b7e.png)

**Comment by amytodd** [comment]
@seif

**Comment by seif** [comment]
@amytodd pretty sure you meant to tag someone else

**Comment by martincf** [comment]
I can't recreate this. Are you still experiencing the issue?
