### ISSUE TITLE
Bug with report record feature

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#490]
Chrome

https://www.layersoflondon.org/map/records/222/report

Weuird bug when you try and get rid of the 'report this record' page and return to the map. It keeps throwing up the form again.

![image](https://user-images.githubusercontent.com/35807842/48552198-bbb6e500-e8cf-11e8-9cc9-1003a7fffd61.png)

**Comment by martincf** [comment]
Yep, I get something similar (report record dialogue window disappears/doesn't appear).

**Comment by edtjones** [comment]
Resolved in earlier release
