### ISSUE TITLE
Issue from user; they are using chrome, i havent noticed it myself

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#493]
Dear Amy,

I am encountering some glitches with the Layers of London map. As I enter new records the map occasionally does one of two things; either it becomes impossible to leave the new record once it has been published or the map freezes and goes blank. It doesn't happen every time but over the last couple of days it has happened quite often. 

I've run my computer cleaner and registry scans to make sure its not my computer playing up and think it must be something to do with the Layers website.

Could you get Ed to check things out please.

**Comment by martincf** [comment]
Yep, I can recreate this on Chrome, Mac too. Have added it to January's milestone for work.
