### ISSUE TITLE
priority: need to edit a record and it is not working

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#494]
![image](https://user-images.githubusercontent.com/35807842/48953076-87c96880-ef3c-11e8-8c4c-fbf4625c0012.png)

Cannot add audio files, it wont add them, it is juts unresponsive

When I try in the back end:

![image](https://user-images.githubusercontent.com/35807842/48953095-9ca5fc00-ef3c-11e8-8139-98f953843f37.png)
  It is not giving me the option to add more?

**Comment by edtjones** [comment]
Can you log in as the owner of the record to edit?

Ed

**Comment by amytodd** [comment]
I am the owner! haha

**Comment by amytodd** [comment]
https://www.layersoflondon.org/admin/records/2073

This one

**Comment by edtjones** [comment]
Looks like you own record Amy - what's the problem editing through the frontend? Or have I misunderstood?

Ed

**Comment by amytodd** [comment]
[cid:image001.png@01D4834B.6DAAC140]

It is unresponsive through the front end when I edit and try add the audio files as attachments?

Thanks

**Comment by edtjones** [comment]
ok - found the issue. It LOOKS unresponsive (that's the bug) but actually it worked! I've added all the mp3s. You'll have to convert the WMAs before you can upload them I think.

**Comment by amytodd** [comment]
Okay great, many thanks, how do I convert the WMA’s? ha

**Comment by amytodd** [comment]
@edtjones I have converted the 3 WMA files but I can't edit the pin and upload them in the front end or go through the back end - there is nowhere to attach new files? Can I send them to you?

**Comment by edtjones** [comment]
Yeah sure. 

--
Sent from my phone: please forgive the brevity.

Ed Jones
