### ISSUE TITLE
issue with teacher function after user testing

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#497]
'Several of the posts have come up as by me, whereas others say ‘by X, student of Ian Stone’. We all followed the link so not sure how that happened? '

From what I can see; all records are under his of Ian Stone and there is nothing to suggest this was a class or students work:

https://www.layersoflondon.org/map/users/125

**Comment by edtjones** [comment]
Can't repeat this @amytodd - please reopen if it's still current
