### ISSUE TITLE
Wider Text Box on Pins

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#50]
We think that a wider format text box would be better as having to scroll down is frustrating for users

**Comment by martincf** [comment]
Can you elaborate, please? Where do you mean? On the record page? The map? Or when adding your content on the Add Record page?

**Comment by selrashidi** [comment]
These are the text boxes that are narrow.


Seif


________________________________

**Comment by martincf** [comment]
Sorry Seif, did you mean to add an attachment to your reply? Can't see anything.

**Comment by andyError** [comment]
Probably no longer relevant.
