### ISSUE TITLE
editing a record - priority

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#500]
![image](https://user-images.githubusercontent.com/35807842/49378438-80f0e180-f704-11e8-81dd-624e426c0bff.png)

Can you please change the sate to 2018 and delete the sentence about 1860 in the description?

It will not save changes when I edit :(

**Comment by martincf** [comment]
Looks like this has been done already?

**Comment by selrashidi** [comment]
I managed to edit the date, so it seems to be working now.
