### ISSUE TITLE
can you change 'teacher functions' to 'organiser functions'

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#502]
and can you let me know when this has been actioned as I need to add some content on this on the website, thanks

**Comment by edtjones** [comment]
Organiser? or Organise?

**Comment by amytodd** [comment]
Organiser sorry


Amy Todd

Public Engagement Officer, Layers of London (http://alpha.layersoflondon.org/)

The Centre for Metropolitan History,

The Institute of Historical Research,

Senate House, London WC1E 7HU

t: 02078628765
e: amy.todd@sas.ac.uk

Twitter: @LayersofLondon

________________________________
