### ISSUE TITLE
About: add page

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#504]
Do you have a suggestion for this like maybe we could have something at the bottom of the page? I dont know

**Comment by martincf** [comment]
Hi Amy. Do you mean a page for him? If so, how about adding a page in the About section?

**Comment by amytodd** [comment]
I am not sure, what do you think would be best? A page or maybe something like on the footer of the page? I am not sure so suggestions would be helpful

Thanks

**Comment by martincf** [comment]
Hi Amy

I think a page in the About section would be the most appropriate.
