### ISSUE TITLE
Records: search fix

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#506]
Hi Amy, can you explain why there is a difference between the number of records returned when I click on Your Records (200) and when I open the First World War Collection (215)?

John

https://www.layersoflondon.org/map/account/account

**Comment by edtjones** [comment]
Hi Amy

The reason is there's a bug in the way we return results from the search engine, which is limiting it to 200 results. Will fix asap.

The correct list is in the 'my account' pane.

Ed
