### ISSUE TITLE
can you please allow us access to change homepage highlights so we can do this regularly to keep it fresh

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#509]

**Comment by mpdavies** [comment]
Hi Amy
Can we not do this via https://www.layersoflondon.org/admin/homepage_highlights ? I think you can add, delete etc?
M

**Comment by amytodd** [comment]
You can delete but you can’t add (from what I see?) When you try it comes up with an error code

**Comment by mpdavies** [comment]
Ah I see... yes we need that fixing. @edtjones ?
Matthew

**Comment by edtjones** [comment]
Now done and live
