### ISSUE TITLE
Cannot close image window and escape from record (Bug)

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#511]
In Chrome.
Select a Record that contains an image
When the record opens, click on the image to enlarge it.
Clicking Close takes you back to the Record
BUT clicking Close on the Record brings up the enlarged image again instead of escaping back to the Map, so you end up in a loop

ALSO

When there are multiple images attached to a Record, you can't use the left and right arrows to browse them when you have opened one of them - you have to click on each image. ie. the arrows don't work.

**Comment by edtjones** [comment]
Resolved in earlier releases
