### ISSUE TITLE
New Map Layers - menu

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#52]
With the new map Layers, we may receive many of these and wondered what format the menu would take (so that we wouldn't get a super long list of map layers).  Could the menu have folders for these additional Layers - to prevent the menu getting too long and hard to navigate.

**Comment by martincf** [comment]
Do you mean on the layers page of the application?

**Comment by selrashidi** [comment]
Yes - exactly. the equivalent of this: 

![layers menu](https://user-images.githubusercontent.com/22592196/39585864-ab5116da-4eed-11e8-88ca-17eb1b6cdbde.png)
