### ISSUE TITLE
issues from user

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#522]
Hi Amy
As mentioned, here are the technical problems which I've come across:

1. Closing after viewing photo/slideshow ribbon ('loop' and workaround) When looking at the photos within a record, the Close function at top right goes into a loop: Close at the photos/slideshow ribbon level takes you to the record at full width - Close at this stage takes you back to the photos/slideshow level again. Workaround: The only way back to the map from the full width record is to click on the name of the contributor.

2. Layers: the slider for the layers (to change the opacity of a selected layer) often doesn't work - the hand and bar disappear, or the hand doesn't react at all.

3. Add media and documents:
- how can I re-order the uploaded images without having to load them all up again in the revised order?
- is there a way of choosing the featured image rather than it being automatically the first one loaded?
- how can I credit people/sources for images when the images in a set are by/from more than one person or source? (eg. see
https://www.layersoflondon.org/map/records/5541 Site of Broad Green cinema)

@selrashidi

**Comment by Nirvikalpa108** [comment]
Reassigned issues.
