### ISSUE TITLE
Records: add thumbnail for attachments

### ISSUE THREAD

**Issue by amytodd** [layersoflondon/application#525]
User has reported that when you add word documents or PDF's to add media it is not working. This is what it looks like when you attach a word file: 
![image](https://user-images.githubusercontent.com/35807842/54757143-8b66b680-4be1-11e9-83af-2a66631f5b8f.png)
 I didn't have an issue with PDF's myself

Thanks

**Comment by edtjones** [comment]
I think that would save, actaully, but there's no meaningful thumbnail for it. We'll add a generic one for documents
