### ISSUE TITLE
Remove duplicate scroll bar if there is only one layer

### ISSUE THREAD

**Issue by Nirvikalpa108** [layersoflondon/application#534]
@andyError two scroll bars show up when one layer is selected. The bottom one currently takes precedence over the top. Let's change this so that we only have one scroll bar if one layer has been selected. Thank you ❤️ 

Here you can see it doesn't impede the user so much when just one layer is selected:
![Screenshot 2019-06-11 at 11 57 45](https://user-images.githubusercontent.com/42121379/59267690-bee63980-8c42-11e9-9cb5-8589bd290a5c.png)

But when multiple layers are selected, you can see the inefficiency of this:
![Screenshot 2019-06-11 at 12 30 25](https://user-images.githubusercontent.com/42121379/59268509-c3abed00-8c44-11e9-9c02-0e5679296b8d.png)

**Comment by andyError** [comment]
Fixed. Now looks like:
![Screenshot 2019-06-12 at 12 47 17](https://user-images.githubusercontent.com/5146825/59348895-3d5cdd00-8d10-11e9-9a0b-6dbba8a10784.jpg)
