### ISSUE TITLE
Remove ability to drag tools box

### ISSUE THREAD

**Issue by Nirvikalpa108** [layersoflondon/application#535]
Currently the tool box can be dragged. Let's remove this as the tool box does not require this functionality. 

This is not a significant bug that should prevent deployment.

![Screenshot 2019-06-11 at 12 01 29 (2)](https://user-images.githubusercontent.com/42121379/59267986-9448b080-8c43-11e9-8add-42d5c445023a.png)

**Comment by andyError** [comment]
Fixed.
