### ISSUE TITLE
Ensuring that the map default is always London

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#54]
Hendrik tried adding a pin in Cambridge and the result is that the map viewer now goes automatically to Cambridge. Can we be sure that no matter what pins are added, the map stays centred in London?

Thanks

**Comment by Forester1** [comment]
In addition, is there a way to ensure that we can administrator control of the content to include whether pins can be made visible or disabled. Thanks

**Comment by Forester1** [comment]
Thanks this has changed back to London as the central default view. Does this default view still recentre on the last pin added?

**Comment by martincf** [comment]
We need to consider how to handle errant non-London records being added to the system (map).

**Comment by edtjones** [comment]
@martincf my view is that we should have an outer bounding box and validate records based on that, showing an error if it's outside that area.

**Comment by martincf** [comment]
I disagree. I think this has to be all London, nothing else. 100% London. It'd completely dilute the impact and focus of input if users can add records anywhere. I would stick to @edtjones suggestion.

**Comment by Forester1** [comment]
I agree with @selrashidi. Having a bounding box to ensure the site is centred on London is important. Limiting contribution to just London area may ensure we miss contextual history points that are related that users want to but are unable to provide.

**Comment by phendrick** [comment]
We'll make the map centre on London for now and move the configuration into an admin interface (#162 )
