### ISSUE TITLE
MARKETING SITE: Sign up form

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#56]
Develop signup page

**Comment by Forester1** [comment]
From @KFlynn1 
At the point of signup users must sign the user agreement - this to be provided by IHR.
Can this signing of the agreement be included as a function within the sign up process. Users must sign the agreement to access a user account upon signup.
@amytodd @selrashidi

**Comment by edtjones** [comment]
@KFlynn1 @selrashidi can we have the text please? cc @martincf

**Comment by KFlynn1** [comment]
Hi,

Apologies I've been on leave and since back have had to focus entirely on an arts award programme I am running next week.

I'm not at work today but can get this to you tomorrow.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by edtjones** [comment]
No massive hurry.

**Comment by KFlynn1** [comment]
The user agreement has been done and is with the legal department. I am just waiting for it to be finalised and will send it on. I will hopefully have an update on this next week.

________________________________

**Comment by edtjones** [comment]
@KFlynn1 I have added a page called 'user agreement' here: http://localhost:3000/user-agreement which you can populate with the text when Legal has signed off on it. The signup form includes a confirmation that the user agrees to it. It has a separate signup for any marketing materials, so we're in line with GDPR best practices.
![screen shot 2018-08-13 at 22 09 21](https://user-images.githubusercontent.com/4377783/44058272-8e90edc4-9f45-11e8-9c8a-74df473a374b.jpg)
