### ISSUE TITLE
Layers picker: Show all layers filterable by preset filters

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#570]
The filter are:

- General Maps of London
- Maps of Specific London Boroughs [This will need a popover to allow the user to select a particular borough]
- Datasets

**Comment by andyError** [comment]
![Screenshot 2020-01-24 at 11 10 05](https://user-images.githubusercontent.com/5146825/73064878-1bc4f600-3e9a-11ea-94af-698023a94a41.jpg)

**Comment by phendrick** [comment]
This is ready for testing on staging
