### ISSUE TITLE
Map: Create guided introduction 

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#572]
![Screenshot 2020-01-24 at 11 20 30](https://user-images.githubusercontent.com/5146825/73065689-17014180-3e9c-11ea-8853-08eb46a4d89b.jpg)
![Screenshot 2020-01-24 at 11 20 36](https://user-images.githubusercontent.com/5146825/73065699-1d8fb900-3e9c-11ea-9833-e275ba2a3bc7.jpg)
![Screenshot 2020-01-24 at 11 21 17](https://user-images.githubusercontent.com/5146825/73065714-241e3080-3e9c-11ea-9559-0a8954846fb8.jpg)

**Comment by phendrick** [comment]
this is ready for FED'ing in the feature/introjs branch.

**Comment by andyError** [comment]
I have FEDed, but could you make it just not happen if the screen width is less than 1151px please?

**Comment by andyError** [comment]
I'm going to create a new ticket for that last bit.
