### ISSUE TITLE
Content Not Found error message

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#575]
Adam getting 'content not found' message again when trying to view records using Chrome: 

layersoflondon.org/map?record=11491

**Comment by andyError** [comment]
It's likely that's just a bad URL. No record exists there. Did Adam follow a link to get there and if so from where?

**Comment by EliWei** [comment]
might have been a record that has now been deleted?

Still have the problem though whether I go through a collection: https://www.layersoflondon.org/map/collections/359?record=11438
Or by the start screen’s map:  https://www.layersoflondon.org/map?record=11143

**Comment by edtjones** [comment]
So that missing record is in still visible in the collection?

**Comment by EliWei** [comment]
Ed, yes it seems like it is @edtjones

**Comment by EliWei** [comment]
Those url:s are now working for me and Ed. Just waiting to hear back from Adam before closing the ticket.
