### ISSUE TITLE
Problems uploading several images

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#576]
One volunteer (solange la rose) has had issues when dragging and dropping several images. She finds the order of the images keeps changing and captions then switch between records  from the edit to the published screen. For the time being I’ve advised her to try uploading images individually.

**Comment by EliWei** [comment]
Have to click out of the caption box or the credit box, otherwise it won't save it.

**Comment by edtjones** [comment]
title, credit and description are now persisted on keyup (with a 1s delay between saves) so things are saved as you type. Rssolved in ecaeaead77109b5f3928a7e65c4bc69de383daa2
