### ISSUE TITLE
Inability to upload images for some users

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#579]
A couple of volunteers have been having issue uploading images using chrome; the first said that images simply wouldn’t upload. I’ve tried logging on as her (--name withheld--) and it seems I can upload images using chrome as her. How do we investigate this further

**Comment by edtjones** [comment]
@EliWei let's ask for an example image. I suspect it'll be too big.

**Comment by EliWei** [comment]
I'll ask Adam

**Comment by EliWei** [comment]
IHR says the user no longer has this issue
