### ISSUE TITLE
Change tagging to OR from AND

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#583]
When you click all of the tags under “education” you get result of zero records, as that would display a story with all of those tags in them. Instead IHR would like tagging setting to OR

**Comment by seanhawkridge** [comment]
@andyError @EliWei I just want to triple-check this is right - because it was originally OR'd, and we changed it to AND.

**Comment by andyError** [comment]
I might have encouraged it moving to AND - if you search for 'video' and 'WWII' you want videos of WWII, not all of both. But if the relevance ranking works - and things which match multiple tags are bumped to the top then it amounts to much the same thing and returns a lot more results.

So OR is good.
