### ISSUE TITLE
Remove layers 

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#584]
IHR would like to switch map layers off so that we don't see them in the layers menu? Not just clicking the eye but removing it completely. 

We currently hass 'choose new layers' and unticking. But IHR feels it is a long way of doing it. They feel the  more logical way is to have an on/off button on the little menu on the map.

**Comment by EliWei** [comment]
From Seif: 
"while there is a way to make map layers on the map disappear on the map, there is no way to switch a layer completely off from the Layer tools menu. Can we please do this? (When you have opened many layers, you end up with a huge long list of layers, which means you can't see the ones you want and it ends up looking cluttered. "

**Comment by andyError** [comment]
I don't think this is very useful to be honest, and not worth adding clutter to this already complex tool. It means that there are little icons for three very similar functions: Hide sublayer, collapse layer, remove layer BUT if it is deemed important then it'll look something like this:

![Screenshot 2020-02-11 at 17 32 25](https://user-images.githubusercontent.com/5146825/74262459-d22b3680-4cf4-11ea-851d-896bd5dd5ebb.jpg)

…with the 'x' to the right.

Do you want to share this with Seif @EliWei ?

**Comment by andyError** [comment]
I've put the rough FED in feature/remove-layer-within-tool

**Comment by EliWei** [comment]
We'll put this on hold until I've heard back from IHR about feature priorities.

**Comment by andyError** [comment]
FED is complete in feature/remove-layer-within-tool, needs Ed or Paul to hookup.

**Comment by mpdavies** [comment]
Close?

**Comment by edtjones** [comment]
Yeah this is done.
