### ISSUE TITLE
Make tagging mandatory for record creation

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#585]
Please making tagging (minimum of one tag) a requirement for creating records. 
 And please notify the LoL team when done, so that they can update the downloadable user guide accordingly.

**Comment by andyError** [comment]
I think we can just have an error if no tags are selected: "Please choose one or more tags."

**Comment by edtjones** [comment]
Probably the easiest implementation is to add a validtion on the association, here https://github.com/layersoflondon/application/blob/master/src/app/models/record.rb#L60

That way the error will appear in the error box on the clientside, the record won't be published, etc.

**Comment by mpdavies** [comment]
done, so close
