### ISSUE TITLE
Half the screen disappears when looking at the maps layer in Chrome

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#586]
This is the same as ticket #574 (now closed)
Elisabeth and Adam still have this issue 

https://www.layersoflondon.org/map/51.5368738497555,-0.25228321552276617

![image](https://user-images.githubusercontent.com/12016064/74026806-370a2800-49a7-11ea-85c6-b4f82b7f924e.png)

**Comment by edtjones** [comment]
@EliWei I can't make this break on my machine in any browser. Don't know how to fix this because I can't see it :/

**Comment by EliWei** [comment]
This works for me now, in Staging
