### ISSUE TITLE
Fix three new CTAs to point to correct places

### ISSUE THREAD

**Issue by seanhawkridge** [layersoflondon/application#588]
Need to remember to point them to the correct place on launch.

**Comment by EliWei** [comment]
Make the Layermaker page have a link to this how to guide: 
https://www.layersoflondon.org/help-  
            centre/guides/layer-making-georeferencer

(It's the same thing, right?)

**Comment by EliWei** [comment]
And can the Booth map tool page have a link to this how to guide: 
https://www.layersoflondon.org/news-events/the-booth-poverty-maps-crowd-sourcing-application

**Comment by andyError** [comment]
I've done the CTAs. And made the links point to those places BUT I'm sure both of those guide pages will put people right off. We should be linking straight to the apps, and letting people search out help if they need it.
