### ISSUE TITLE
Hyperlinks don't work

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#590]
When you have data sets (e.g. furniture makers or HER data) the hyperlinks don’t link – If you click on the yellow box it closes, whereas actually what you want is for the hyperlink to take you to the page. Is there a way to do this?

![image](https://user-images.githubusercontent.com/12016064/74244243-668b9e00-4ce1-11ea-9cf0-f8769d2b5974.png)

**Comment by andyError** [comment]
Might be tough.

**Comment by edtjones** [comment]
We could do it if we agreed which field in the vectors was to be hyperlinked. If we use 'hyperlink', the change needs to happen in here: https://github.com/layersoflondon/application/blob/master/src/app/frontend/components/vector_grid_feature.js in the `content` const. We need to check if the `key` matches 'Hyperlink' (probably good to parameterise that somewhere) and add an <a> around the `value` if so.

**Comment by phendrick** [comment]
this is in feature/dataset-hyperlinks-in-overlay - if we can get confirmation that dataset attributes will match, we can  merge it

**Comment by edtjones** [comment]
I've amended the code so we match on any value in a dataset overlay which starts with 'http' - I think that's plenty of specificity.

This is ready to QA. A good example layer to add would be https://staging.layersoflondon.org/map/?layer=furniture-makers-1640-1840&layers=true

![Screen Shot 2020-02-21 at 13 29 24](https://user-images.githubusercontent.com/4377783/75038457-50829800-54ae-11ea-82f5-ce6156154398.jpg)

**Comment by andyError** [comment]
That's what I suggested ^ and you told me it was a nasty way of doing it :)

**Comment by EliWei** [comment]
I get this to work on the Furniture makers. However, when I use the Listed Building's layer, the hyperlinks do work in the sense that it takes me to Historic England, but then they just time out. I expect this is not an issue on our end, but should we notify someone?
https://historicengland.org.uk/listing/the-list/list-entry/1241988 for example.

**Comment by edtjones** [comment]
Seems to have been a transient issue at the HE site; closing.
