### ISSUE TITLE
Search: Tag selection issues

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#591]
![Screenshot 2020-02-11 at 17 40 38](https://user-images.githubusercontent.com/5146825/74262914-b07e7f00-4cf5-11ea-9f09-cc20eccd5816.jpg)

If you
open the search
click the health tag box
click 'select all'
then click on the individual checkboxes

You'll find that you can't turn them off individually, and the label count goes up higher than it should be possible to (up to 12 in the screenshot).

**Comment by phendrick** [comment]
fixed in development
