### ISSUE TITLE
Add record: Missing info in error box?

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#594]
Should this error box tell you what is missing?

![Screenshot 2020-02-11 at 18 37 54](https://user-images.githubusercontent.com/5146825/74267303-b7a98b00-4cfd-11ea-893c-7c68e0efc6c9.jpg)

If I click Add Record and then scroll straight down to the bottom the box looks like this (on live).

**Comment by phendrick** [comment]
fixed in development
