### ISSUE TITLE
Increase zoom on the map to 18

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#599]
We said: We could increase the max zoom on the map to 18 (currently 17) relatively easily, but you'll need to re-render any raster map which doesn't have tiles for zoom level 18, because otherwise at max zoom that map will disappear from view.

Lewis said: Please increase zoom to 18. (I will fix any maps that are currently on zoom 17)

**Comment by edtjones** [comment]
I have increased the max zoom to 18, it's on staging ready for QA.

**Comment by andyError** [comment]
This hasn't worked. Staging and live have the same max zoom.

Staging:

![Screenshot 2020-02-25 at 14 42 15](https://user-images.githubusercontent.com/5146825/75257594-1b8f8180-57dd-11ea-997d-f4ac2910d2da.jpg)

Live:

![Screenshot 2020-02-25 at 14 41 59](https://user-images.githubusercontent.com/5146825/75257614-20eccc00-57dd-11ea-8e8d-8de99f7b4a2e.jpg)

**Comment by edtjones** [comment]
I have now properly amended this zoom issue, and it's on staging for QA.

**Comment by edtjones** [comment]
Resolved in f369cc0679e345caf3e26c1f99c0f18ec05b3d57
