### ISSUE TITLE
Review Seif's document regarding contributor guidance instructions

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#60]

**Comment by andyError** [comment]
@martincf know what this is?

**Comment by selrashidi** [comment]
Describe what in 250 words or less your entry is about
Help with what to write. 

To make it easier, think about:

What is most interesting about your story?
Remember that not everyone knows your area – so describe what can’t be seen.  
Be as specific as you can – Link: The Simpson Family Christmas 1954 
Details make this story memorable

How have things changed over time?  Describe things that are different from today
Link to pin: Family life at the turn of the century
Link to pin: Austins Joinery then, terraced houses now
Sometimes what is remarkable is that things survive for so long.
Link to pin: The Birdcage Pub 
Mulberry tree at Sayes Court Park

Are there any images, files or links you could add? 
They help add valuable detail
Link to pin: Seager Bookshop Early Days
