### ISSUE TITLE
Increase frequency of updating the Layer Maker page

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#601]
Only reviewers should be able to amend an already georeferenced image (rather than anyone who clicks on the image after it has been done).  Could this be done (restricting the modification of georeferenced image to the original contributor or the reviewers?

Is this a problem that the image is still available on the LayerMaker page after it has been georeferenced? Images which are 'done' shouldn't appear.

**Comment by edtjones** [comment]
I've added a scheduled job to run this every 6 hours.
