### ISSUE TITLE
Layer tools widget: Check that layer stacking order is the same in the list as on the map

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#602]
In the layer tools box, the topmost layer sits at the bottom of your layers maps list (rather than the reverse). It’s also not obvious that layers can be moved around (until you try to fade them in and out) – perhaps they could be numbered or have arrows to indicate which map/s is/are on top of each other.

**Comment by edtjones** [comment]
@EliWei Can we go back to the Layers team to confirm how to repeat this? 2 Screenshots attached, which show it working as I would expect, namely:

- I chose the 1940's OS maps and the Chapman Essex Map
- I put the Chapman map at the bottom of the list, and that's reflected in the view on the screen

![Screen Shot 2020-02-21 at 13 59 35](https://user-images.githubusercontent.com/4377783/75040474-9f323100-54b2-11ea-864d-10bb75bc5dee.jpg)

I then changed the order and the Chapman map was at the top in the list, and also at the top on the page:

![Screen Shot 2020-02-21 at 13 59 50](https://user-images.githubusercontent.com/4377783/75040508-ae18e380-54b2-11ea-9ee3-3541face893f.jpg)

**Comment by EliWei** [comment]
Doesn't work in Chrome - the layers are still reverse

**Comment by andyError** [comment]
I'm surprised, but this does seem to be an issue in Chrome and Safari. It works as you'd expect in FF.

I recreated it by:

- Go to map
- Close tray
- Click Hide Markers in Layer tools
- Click Choose new layers
- Choose Bomb Damage and Morgan Map
- Click I'm done

Then:

The order appears correct at first:

![Screenshot 2020-02-25 at 14 11 11](https://user-images.githubusercontent.com/5146825/75254723-b5086480-57d8-11ea-8e52-9a138e141d77.jpg)

…but as soon as you do any interaction, even dragging Bomb Damage and returning it to its spot, the order seems to become reversed:

![Screenshot 2020-02-25 at 14 11 40](https://user-images.githubusercontent.com/5146825/75254830-df5a2200-57d8-11ea-8001-c394f25f48f1.jpg)

(Morgan being under bomb damage in that screen ^)

**Comment by edtjones** [comment]
This is resolved on staging (in Chrome and other browsers) - for QA please @EliWei

**Comment by EliWei** [comment]
Works for me! I'll close it.
