### ISSUE TITLE
The layer tools bar should pop up when you switch on a new map 

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#603]
as it’s not obvious that the option to fade or turn maps on and off , or that it can only be done here.

**Comment by edtjones** [comment]
I've deployed this to staging for QA. Note that there's some subtlety here - if the user has _chosen_ to close the layer tools, it would be annoying for it to keep opening up again, so we track that.

In other words, if you choose a layer, it'll pop open. If you close it, then choose another layer as well, it won't re-open. You'll have to do that yourself. This feels like the best combination.
