### ISSUE TITLE
Layer tools: When you try to move the opacity slider the layer is dragged for reordering instead

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#604]
When you have more than one map uploaded the fade in/out is much harder to use and maps move up and down rather than fade in and out.

**Comment by andyError** [comment]
![Screenshot 2020-02-25 at 13 49 35](https://user-images.githubusercontent.com/5146825/75253099-d0be3b80-57d5-11ea-9f57-747edaf10c63.jpg)

So you get this sort of thing going on ^.

**Comment by edtjones** [comment]
I've resolved this (on staging for QA), but making only the header of the layer group draggable. That's the only reasonable solution, and I think it works ok.
