### ISSUE TITLE
Ensure that the guide works on tablets

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#605]
The instructions need to be slightly different (add a record)

**Comment by andyError** [comment]
The whole guide needs to be somewhat different, unfortunately. Here's what I'd suggest, @phendrick can let you know effort required.

![lol-intro-guide-tablet](https://user-images.githubusercontent.com/5146825/75259440-f3ede880-57df-11ea-8914-2497718c68ac.jpg)

**Comment by mpdavies** [comment]
need to flag as an issue that would be considered when/if migrating to HUMAP, given that Layers is not the same as other HUMAP projects.

**Comment by edtjones** [comment]
We need to consider this on Humap, but I'm going to close here.
