### ISSUE TITLE
Layers picker: Searching clears chosen layers

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#607]
If I select a few layers:

![Screenshot 2020-02-25 at 13 45 22](https://user-images.githubusercontent.com/5146825/75252774-38c05200-57d5-11ea-80ee-bb5ae330fb59.jpg)

and then do a search, they become unselected:

![Screenshot 2020-02-25 at 13 45 34](https://user-images.githubusercontent.com/5146825/75252865-63aaa600-57d5-11ea-8f36-09540bdda44e.jpg)

**Comment by edtjones** [comment]
resolved in 595f0904665578b057b527908d5cd6fb8c9fbb44 and on staging
