### ISSUE TITLE
Layers picker: Boroughs popover needs to be closeable

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#609]
Ideally a click anywhere else on the screen would close this popover, but it should at least close when you click the button again. And I THINK it would be best if it closes once you click a borough.

![Screenshot 2020-02-25 at 15 16 54](https://user-images.githubusercontent.com/5146825/75260904-2ef11b80-57e2-11ea-980d-03099fb5aad2.jpg)

**Comment by edtjones** [comment]
Resolved on staging (and QA'd by @andyError ) in 0b49b82daf2c8c2865edefae1cca997428a674b7
