### ISSUE TITLE
Layers picker: When using filters, featured layers should still display

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#610]
Just because it's a bit jarring when they disappear, for seemingly no reason.

![Screenshot 2020-02-25 at 15 20 24](https://user-images.githubusercontent.com/5146825/75261013-6364d780-57e2-11ea-8d41-5a4a3f7b703a.jpg)

…so at present when you click a borough the featured layers above disappear.

**Comment by edtjones** [comment]
We subsequently agreed that highlighted layers should only appear if 'all' is checked, and there is no free-text query. This is implemented in in 595f0904665578b057b527908d5cd6fb8c9fbb44 and on staging (and QA'd)
