### ISSUE TITLE
Layers picker: Current filter button (All, Borough, Datasets) should be highlighted

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#611]
Styles are in, they just need an 'is-current' on the `<li>` . All should be highlighted by default.

![Screenshot 2020-02-25 at 15 29 37](https://user-images.githubusercontent.com/5146825/75261944-b1c6a600-57e3-11ea-8c79-7feb34fd1781.jpg)

**Comment by edtjones** [comment]
Resolved in 595f0904665578b057b527908d5cd6fb8c9fbb44
