### ISSUE TITLE
Layers picker: I can't see 'Datasets' on the tab filter

### ISSUE THREAD

**Issue by andyError** [layersoflondon/application#612]
Even though I have marked some layers as a 'dataset' in the admin, and reindexed. Probably just me, but could this be checked.

![Screenshot 2020-02-25 at 15 23 43](https://user-images.githubusercontent.com/5146825/75262485-81cbd280-57e4-11ea-879b-1e59840f09d0.jpg)

**Comment by edtjones** [comment]
Resolved on staging; this is a data issue but the resolution happened in 595f0904665578b057b527908d5cd6fb8c9fbb44
