### ISSUE TITLE
Clicking 'Collections' just gives an error message

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#621]
If I'm on the map, and click 'Collections' on the left, nothing happens. (On Staging.)
If i got the tray open, and I click 'Collections', it just says 'O collections'

![Screenshot 2020-03-18 at 12 19 58](https://user-images.githubusercontent.com/12016064/76955789-1e305300-6913-11ea-8e9d-feb12445d1f3.png)

**Comment by edtjones** [comment]
Resolved in 89b1cdb8a25a3437485bf03cb5e1862592f74c96

**Comment by edtjones** [comment]
(and deployed)
