### ISSUE TITLE
Introduce the ability to feature certain collections of maps / override chronology

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#627]
When a borough is selected in Borough Maps, we want to be able to prioritise the collections of maps provided by the borough archives. The problem at the moment is that the results look random -  I’m guessing that they are based on date range? We don’t mind if most of them are organised by date, but we do want to be able to have some maps at the top of the results. Is there a way to eg. tag those maps we want to appear first?

**Comment by edtjones** [comment]
This is on staging for QA, @EliWei . I've also done the ordering of the filters and set 'london maps' as the default. I couldn't find a ticket for that.

**Comment by EliWei** [comment]
Thanks @edtjones 
So can IHR now go in and override chronology from the Admin end?

**Comment by edtjones** [comment]
Yes, I have reused the 'highlighted' tickbox. So highlighted things, which are also borough maps, are now pinned to the top of the list

**Comment by EliWei** [comment]
thanks!
