### ISSUE TITLE
New image at the top of Layers Maker Page

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#630]
on the Layer maker page, we think it would be good to replace the current image at the top of the page with an image that gave context to the page. We were thinking that perhaps the mosaic of the aerial photos was a good one to have? I have attached a rough idea of what I mean. 

It could also have three images showing the evolving georeferencing exercise. 
![Layer Maker](https://user-images.githubusercontent.com/12016064/77652757-0f7b1900-6f6f-11ea-8ce8-37281d886e2f.jpg)

**Comment by EliWei** [comment]
Here is the giphy showing georeferencing po that Adam made

https://giphy.com/gifs/raf-1949-aerialphotography-layersoflondon-UtPF1g8ZXoJyy0XSuz

**Comment by andyError** [comment]
I've just done it as an image for now, I think having something animated is a nice idea, but would be a bit distracting if applied in the background.
