### ISSUE TITLE
Turning off the layers function

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#631]
Layer Tools menu - while there is a way to make map layers on the map disappear on the map, there is no way to switch a layer completely off from the Layer tools menu. Can we please do this? (When you have opened many layers, you end up with a huge long list of layers, which means you can't see the ones you want and it ends up looking cluttered. 

We've looked at this and we don't think this is very useful, and that it's adding clutter to this already complex tool. It means that there are little icons for three very similar functions: Hide sublayer, collapse layer, remove layer. Seif still wants to go ahead. ("I think it is useful because the current set up can be frustrating (not being able to unsee things on the menu.  As such, can we go ahead with it?

Adam feels that a pop up that says ' are you sure you want to remove this' that came up when you press the X would be good, not sure how feasible that would be.")

**Comment by edtjones** [comment]
This is resolved in Humap

**Comment by mpdavies** [comment]
I think we leave this pending decision about migration.

**Comment by edtjones** [comment]
I'll close this given we're going ahead with the migration
