### ISSUE TITLE
Descriptions aren't adding properly

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#636]
when adding descriptions to images, these descriptions aren't adding properly - the description for one of them appears over multiple images, deleting any descriptions that have already been typed in.

**Comment by EliWei** [comment]
Nor are image credits

**Comment by edtjones** [comment]
I can't repeat this - it's working ok for me. Need more detailed instructions.

**Comment by mpdavies** [comment]
ok, but need to capture these and other issues to ensure they are monitored in HUMAP if we migrate

**Comment by edtjones** [comment]
I'll close but leave the labels. We should do a pre-migration checklist from them.
