### ISSUE TITLE
Issue with allowing a new team to edit

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#644]
Sometimes when trying to add a team in the 'Who can edit' part of the add record, the option to do so doesn't stay open long enough to allow you to pick a team. 

(EW's got a video showing the problem)

**Comment by mpdavies** [comment]
among the various issues with creating and running teams. Has this been looked at? Appreciate that it may be solved via HUMAP but if there's a quick fix then it would at least stop this particular frustration

**Comment by edtjones** [comment]
I found a chrome-only bug today which I've fixed and deployed.
