### ISSUE TITLE
Yellow box info not appearing

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#646]
When viewing the map, if you upload more than one dataset (e.g. the HER and the London Archaeological Investigations layers), the info in the yellow boxes won't appear if you have a collection of records visible as well (eg.the London Archaeologist articles collection). The only way to be able to view these is to hide the records - this might just be a time delay and data overload?

**Comment by mpdavies** [comment]
this has been mentioned before in another issue #669

**Comment by edtjones** [comment]
As with #669 I'm going to close this and we can review in Humap
