### ISSUE TITLE
The yellow edit word not working

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#647]
A couple of volunteers have also complained that the yellow edit word on the record page hasn't been working when they've tried to go and re-edit a draft record. I've tried logging in as them and checking this but it worked fine for me. Until today... when I was demonstrating how to re-edit a record in a training session, and for some reason it didn't work. (The only thing I could think of was that I was saving and re-editing a few times to show different stages of editing records, but I'm not certain this caused it.)

**Comment by EliWei** [comment]
A couple of volunteers have told me they're encountering problems editing records. 
Again, it seems quite temperamental, but the issue is that the yellow edit buttons don't work, neither when going via the 'my profile' pages, nor via 'my records'.

I've tried logging on with both of their accounts and all works fine when I try. So i'm wondering whether this might be a local thing relating to their PCs/laptops. I've suggested they try different browsers. For one this worked at first but then failed again. The other hasn't replied yet.

The first volunteer when trying to view/edit his records was also getting the 'Content not Found. There is no content at this address. If you think this is a mistake please get in touch.' error message that I used to get sometimes on my Senate House computer.
I suggested it might have something to do with his cookies?

**Comment by EliWei** [comment]
If you go into Your Profile and look at your records, which is in draft, the edit button does not work. 
![Screenshot 2020-08-26 at 12 26 36](https://user-images.githubusercontent.com/12016064/91292966-98ed7c00-e797-11ea-9ab6-6c9e59ebe8e6.png)
![Screenshot 2020-08-26 at 12 26 12](https://user-images.githubusercontent.com/12016064/91292976-9c810300-e797-11ea-9e08-3b3e24a3ffa7.png)

**Comment by edtjones** [comment]
More investigation needed - estimate this is a medium difficulty issue.

**Comment by mpdavies** [comment]
any news on this one?

**Comment by edtjones** [comment]
I have done some investigation on this, and can't make it break. The way this works is a bit funky, and it's possible that there are certain browsers which don't work, although I can't make it fail.

Suggest we close this, because it's not affecting a majority of users, and we'll be doing something different in Humap.
