### ISSUE TITLE
Note detail overlay needs a bit of design love

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#65]
@foxpaul has done a VALIANT job getting the overlay working but I think the layout could do with a little bit more love. Screenie for dataset attached.
![screen shot 2016-12-08 at 22 28 27](https://cloud.githubusercontent.com/assets/4377783/21030311/c788d3dc-bd95-11e6-94c4-b0295a043525.png)

**Comment by andyError** [comment]
I've smartened it up a bit, going to leave for now as this will soon be recreated in React.
