### ISSUE TITLE
Deploy zoom level 19 to maps

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#654]
Maps have now been re-tiled, so we can go ahead and enable the higher level zoom.

There is also a question whether detection of the existence of tile directories above Z-18 for each layer would allow setting of the maxNativeZoom attribute, thereby ensuring that layers do not disappear at higher levels? Failing that, perhaps it could be set globally at Z-18, and overridden for specific layers?

**Comment by edtjones** [comment]
It's not possible to do zoom per overlay because you'd have to dynamically change the max zoom for the map depending on which layers are selected, but I have set the zoom to 19 globally
