### ISSUE TITLE
Records disappear

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#655]
https://www.layersoflondon.org/map/collections/531
https://www.layersoflondon.org/map/collections/527

When I go to edit the collections in question, a number of associated records initially appear, however after a few seconds they are disappearing.

search in the 'records' bar to add a record to the collection.

Adam said a similar issue was reported in April and said it had been sorted by making sure we reindex associated collections when you change the state of a record from draft to published?

**Comment by edtjones** [comment]
@EliWei is this in the admin interface or on the frontend? I don't know where 'the records bar' is.

**Comment by EliWei** [comment]
@edtjones It's the admin interface. I've sent you en email with screenshots

**Comment by EliWei** [comment]
And here as well:
I've uploaded everything to a new collection called Lesbian London, Past and Present. The current collection shows 15 items, however, there should be 16 items.
For some reason, this item does not appear in the collection: https://www.layersoflondon.org/map?record=14606

**Comment by EliWei** [comment]
Again, on the 20th of Aug: "I am getting in touch again about a recurring problem with the collection 'My Own Story' I reported below a couple of months ago. It is the same issue with records appearing in the collection on the admin site but then disappearing."

**Comment by EliWei** [comment]
I've uploaded everything to a new collection called Lesbian London, Past and Present. The current collection shows 15 items, however, there should be 16 items.
For some reason, this item does not appear in the collection: https://www.layersoflondon.org/map?record=14606
(email to Elisabeth on 3rd July)

**Comment by EliWei** [comment]
Four records now showing for 'My own Story' (the 4 records appearing are 'The Dukes Head 1962', 'Guildhall School of Music (Old Building)', 'House of Commons 'My Own Story' by Emmeline Pankhurst', and 'Caxton Hall, Westminster - 'My Own Story' by Emmeline Pankhurst) but 'The dukes Head' is by another author and is irrelevant to the Collection. 

Hence, not all of the records are showing and incorrect records are now also associated with the collection. 
![Capture1](https://user-images.githubusercontent.com/12016064/91154726-23fc4280-e6c2-11ea-89be-69535024f8d8.PNG)

**Comment by edtjones** [comment]
Conflation of a number of different issues I think.

- Sisterwrite is now on the Lesbian London collection. I don't know whether this is a non-problem or whether something has changed since the error report.
- My Own Story now only contains 2 records.

Hard to know how to pursue this.

**Comment by mpdavies** [comment]
any more information on this? If not then we can't pursue unless there are further examples

**Comment by edtjones** [comment]
I'm going to leave this one flagged as wont-fix for now @mpdavies
