### ISSUE TITLE
House of Commons, "My own story" by Emmeline Pankhurst

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#656]
The "to date" is displayed incorrectly.

**Comment by EliWei** [comment]
![Capture4](https://user-images.githubusercontent.com/12016064/85701388-a0cc6980-b6dd-11ea-99d3-858c6c6e618b.PNG)
![Capture3](https://user-images.githubusercontent.com/12016064/85701392-a1fd9680-b6dd-11ea-8607-fbaf745d39c6.PNG)

**Comment by edtjones** [comment]
This record had a day and year (but no month) set for the end date. I've removed it.
