### ISSUE TITLE
Record appearing twice in a collection

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#657]
when I am viewing a collection and I click into a record, after I close the record and look at the collection again, the record I was looking at now appears twice. There seems to be a good few problems with the catologing of collections at the moment. 

![One](https://user-images.githubusercontent.com/12016064/86474950-1b336400-bd44-11ea-8840-80293bfd9efb.png)
![Two](https://user-images.githubusercontent.com/12016064/86474944-1a023700-bd44-11ea-8dc8-b9623f872370.png)
![Three](https://user-images.githubusercontent.com/12016064/86474931-166eb000-bd44-11ea-97a5-0191f11af4a3.png)

**Comment by edtjones** [comment]
Can't repeat this.

**Comment by mpdavies** [comment]
ok, let's keep an eye out for repeats

**Comment by edtjones** [comment]
I think this was a transient issue with the search indexing. Closing (but keeping the labels)
