### ISSUE TITLE
Colour coding pins

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#66]
From @amytodd can we add the ability to colour code pins within a collection?

**Comment by amytodd** [comment]
For example a user wanted to create a collection if a High Street and colour code the types of shops (butchers etc), Thanks
________________________________

**Comment by Forester1** [comment]
Whilst this is an open issue, can we consider the addition of default multi-hue sequential or diverging colours. It will simplify the categoric selection for the user and keep the site and cartographic design consistent.

**Comment by Forester1** [comment]
For example some of the schemes from http://colorbrewer2.org

**Comment by edtjones** [comment]
There are some usuability / accessibility issues with relying on differentiation by colour alone, which we should consider. We might want to choose some other identifying features in addition / instead (like shape?). @andyError @martincf and I will discuss.

**Comment by andyError** [comment]
We're going to close this, I don't think colour coding has any current useful applications, considering the drawbacks.
