### ISSUE TITLE
'overlay found' link caret needs reversing when open

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#66]
When the 'overlay found' button is clicked so the overlays list is in view, we should reverse the caret / triangle.
![screen shot 2016-12-08 at 22 30 32](https://cloud.githubusercontent.com/assets/4377783/21030339/f3712760-bd95-11e6-8824-8bd383cfbb80.png)

**Comment by martincf** [comment]
Can you give us a bit more idea of what you'd expect the colours to symbolise?
