### ISSUE TITLE
Unable to upload pdf

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#662]
Please check you've included these in your issue:

- [ ] A title which summarises the problem or describes the desired outcome

If this is a bug or something is broken:

- [ ] A description which explains how to repeat the problem
- [ ] Information about the browser (e.g. Chrome), version (e.g. 54) and platform (e.g. Windows) where you had the problem
- [ ] A screenshot of your problem. Find out more here: https://www.take-a-screenshot.org/
- [ ] A theme label of _bug_

If this is a suggestion, question or future development idea:

- [ ] A description which explains your issue
- [ ] An appropriate theme label

**Comment by EliWei** [comment]
However, I did a test trying to upload a different pdf to a different record but that too produced this page:
![image (1)](https://user-images.githubusercontent.com/12016064/89988788-5482bc00-dc80-11ea-96f0-f885332b0631.png)

**Comment by edtjones** [comment]
The url here has the domain in it twice. What's the ID of the record with the pdf?

**Comment by mpdavies** [comment]
not clear

**Comment by edtjones** [comment]
I found the bug and resolved it - the link on the page had the domain twice.
