### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#663]
I get a server error on the georeferencing guide page
https://www.layersoflondon.org/help-centre/guides/layer-making-georeferencer
![Screenshot 2020-08-13 at 15 48 58](https://user-images.githubusercontent.com/12016064/90142349-8bd69300-dd7c-11ea-84b9-370fcaa24f9e.png)

**Comment by edtjones** [comment]
This was actually a 404, which wasn't being caught properly. Resolved as part of 97e3c14291def871f5ed80e0ff143e5852f3409f
