### ISSUE TITLE
One layer can't be in more than one layer group

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#664]
one layer can't be included in more than one layer group. For example, if you had a map of Essex that you wanted to include in the Havering group with all the other local maps of Havering, but also wanted to include it in the Redbridge group, with Redbridge's local maps, at the moment you can't do this.
It appears that layers can only be assigned to one Borough layer group, regardless of which boroughs they're tagged as

**Comment by edtjones** [comment]
We need to change the associations between layers and layer groups to facilitate this.

**Comment by mpdavies** [comment]
I *think* this was mentioned as being straightforward to fix?

**Comment by mpdavies** [comment]
see previous comment - we discussed in Oct and I thought that we were going to sort this one, ie allow a one-many relationship between layers and layer groups.

**Comment by edtjones** [comment]
I've just deployed this and it's working well - you can add layers to more than one layer group now.

**Comment by mpdavies** [comment]
great, thanks Ed
