### ISSUE TITLE
yellow dataset boxes of information not working when you have a collection uploaded

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#669]
Hi Elisabeth,
Attached is the video showing the issue of yellow dataset boxes of information not working when you have a collection uploaded, unless you hide the records.
Having just run a few further checks, I wonder if it's related to the size of the collection? This said I don't think it's a time delay issue as I waited a good minute when data wasn't showing and still nothing appeared.
Thanks
Adam

Test 1) London Archaeologist collection (707 records) and London Archaeological Investigations layer (see video) 
Result, records need to be hidden to view dataset info
(these two go hand in hand so would be good to fix)

Test 2) Dickens London collection (9 records) and dickens layer
Result: data is visible regardless of whether records are shown or hidden

Test 3) London Archaeologist collection (707 records) & dickens layer
Result, records need to be hidden to view dataset info

Test 4) Dickens London collection (9 records) and London Archaeological Investigations layer
Result: data is visible regardless of whether records are shown or hidden

Test 5) London Pubs collection (1202 records) and London Archaeological Investigations layer
Result, records need to be hidden to view dataset info

Test 6) London Pubs collection (1202 records) and dickens layer
Result, records need to be hidden to view dataset info

**Comment by EliWei** [comment]
Ask Elisabeth for video

**Comment by edtjones** [comment]
This is probably too complex to resolve in LoL but it works in humap.

**Comment by mpdavies** [comment]
OK, leave for now pending decision re. migration

**Comment by edtjones** [comment]
I'll close this but leave the labels so we can make sure it works ok in humap
