### ISSUE TITLE
Georeferencer: finished button appearing at wrong time

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#67]
From @selrashidi : While reviewing the georeferenced images is that the button that says "It looks like this map is finished" appears too soon, leading to images which are not as accurate as they could be.

Is there any way it could be adjusted not to appear so fast. (For example to appear after 10 points have been georeferenced)?

**Comment by edtjones** [comment]
This is a sticking point in Klokan's implementation - closing because there isn't anything we can do about this.
