### ISSUE TITLE
Unable to add image to record

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#671]
Record - https://www.layersoflondon.org/map?record=16327

I am unable to upload images to the record
there also seems to be an issue with it registering the changes I make when I click 'save'

**Comment by edtjones** [comment]
The image is in webp format which isn't supported.

**Comment by mpdavies** [comment]
see comment on #672

**Comment by edtjones** [comment]
I've scoured the web and found a higher-res version of the image from Penguin, which I've added to this record.
