### ISSUE TITLE
Record in Collection not showing on the front-end

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#672]
Collection - https://www.layersoflondon.org/map/collections/615
On the admin site it appears as if the (above) record is in the collection

On the website it isn't appearing

I am also unable to save changes I am trying to make to the collection, including changing it to a collection anyone can add to, and updating the description.

When I try and update it on the admin site, I keep getting this [Error 502 message] page

![Capture](https://user-images.githubusercontent.com/12016064/95194284-604cb380-07d5-11eb-8d3c-4eea99c3fa4a.PNG)
![Capture2](https://user-images.githubusercontent.com/12016064/95194280-5e82f000-07d5-11eb-89c5-c4f5d626cfe0.PNG)
![Capture3 (1)](https://user-images.githubusercontent.com/12016064/95194275-5d51c300-07d5-11eb-927e-44e31b2fd97d.PNG)

**Comment by edtjones** [comment]
The record has an image associated with it which is in .webp format, which we can't handle. We need to change to png.

**Comment by mpdavies** [comment]
Seems like a quick fix, so ok. If the image format is the problem, then it would make sense if a record can only be created and saved if attachments are in supported formats. Not for Layers#1 but will HUMAP do that?

**Comment by edtjones** [comment]
I've fixed this by uploading a working image to the record. It now appears in the collection.
