### ISSUE TITLE
Records not visible when not logged in

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#675]
Currently, if I don't log in (either with my own account or with [name withheld]'s token the only record visible in the collection "Medieval Londoners" is Messuage opposite Oystergate. Why is my record A dwelling house in St Benet Gracechurch not visible to the general public when it is in the Medieval Londoners collection and [name withheld] did mark it as "Published"?

**Comment by edtjones** [comment]
I think this was just the time taken to reindex the collection. I can see it both in the collection and on its own now:

![Screenshot 2020-11-26 at 14 10 30](https://user-images.githubusercontent.com/4377783/100360730-410e1d80-2ff1-11eb-959e-7f9062e75f86.jpg)
![Screenshot 2020-11-26 at 14 10 37](https://user-images.githubusercontent.com/4377783/100360736-43707780-2ff1-11eb-8be9-bd4708754161.jpg)
