### ISSUE TITLE
Credit for students (Teams vs. Token)

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#677]
When [name withheld] marks my draft records (those make using her token) into "Published" my name no longer appears in the byline - is there any way to change this?  

 

How can we get the collection called "Medieval Londoners" to appear in this dropdown menu? 

 

Should [name] just tick the "Anyone" button in the "Edit collection" screen and we just hope for the best that no one outside of our class adds records to this collection until the semester is over? Or @[name] can you actually click into this dropdown and set it so that only members of the team Medieval Londoner's can edit? (I have tried to use that drop down with no success so far). 

If we could get that to work it would be better than using the token as that seems to remove students' names from the byline. We would like to use the teams option (and have [name] invite all of the undergraduates to be part of a team called Medieval Londoners), but if the students can add records to the Medieval Londoners collection by themselves that creates a lot of work for [name] on the back end.

**Comment by EliWei** [comment]
![image001](https://user-images.githubusercontent.com/12016064/100356779-fe9a1000-2ff3-11eb-8aae-5eb098baa6b6.png)

**Comment by EliWei** [comment]
![image002](https://user-images.githubusercontent.com/12016064/100356802-05c11e00-2ff4-11eb-90b7-4fdec1c5ebfc.png)

**Comment by edtjones** [comment]
This is resolved by fixing the 'members of' dropdown.

Students should have their own account and be members of the team - that way they'll get the credit.
