### ISSUE TITLE
get the dropdown options to show

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#679]
One thing that would help us a lot is if you could get this dropdown to work, but for the collection called Medieval Londoners ([name] is the owner of that one so I can't edit it). We would like the collection called Medieval Londoners to be editable by anyone in the team called Medieval Londoners but the dropdown doesn't seem to be working. I can get the dropdown options to show, but I can't actually click on any of them.

If you could help us with that first it would remove the need for several of my other questions. Unless you have other suggestions for how best to work on a collection with 19 students contributing!

**Comment by EliWei** [comment]
![image (4)](https://user-images.githubusercontent.com/12016064/100358302-4883f580-2ff6-11eb-9f29-77bfaf202e8b.png)

**Comment by edtjones** [comment]
resolved in f78835209a55abf7dc74bfff8275e3bdbe60700f
