### ISSUE TITLE
Sticker Query

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#683]
Change the Heritage Fund sticker throughout Except where noted and excluding company and organisation logos this work is shared under a Creative Commons Attribution 4.0 (CC BY 4.0) Licence 

Please attribute as: “Layers of London (2020) supported by The National Lottery Heritage Fund, licensed under CC BY 40”

=> Elisabeth has the full email conversation

**Comment by edtjones** [comment]
Now deployed
