### ISSUE TITLE
Hosting question

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#72]
From @amytodd :
are we right in thinking you are hosting this and the information uploaded on the website? we need to confirm this for our permissions form/code of conduct on the website to make this clear to users

**Comment by edtjones** [comment]
Yes @amytodd that's correct. The only exception to this is:

 - where we offload images to a third-party service like AWS S3
 - where videos and audio are uploaded to Youtube / Soundcloud

fundamentally though these are both implementation details, and the Layers site is the source and store of the data.
