### ISSUE TITLE
Georeferencer: organisation of maps per borough

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#73]
From @selrashidi : 
Georeferencer - we thought about the organisation of maps per borough - we think that there should be a borough folder in which there is a sub folder for maps, and another for aerial photos... would it be possible "to search the base map to enable the searcher to find the aerial photos of the place they were looking for". I think he meant this in terms of "Is there a way you could search for a specific image to georeference based on a place of interest to you?"

**Comment by andyError** [comment]
@edtjones
