### ISSUE TITLE
searching of notes

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#75]
Does the search engine search the notes properly? Of the 2 notes on the site, the note on Parsloes park is returned, but not the one for St Paul's.

**Comment by edtjones** [comment]
Paul's having a look at this.

**Comment by edtjones** [comment]
@foxpaul this looks like erroneous data in the Rails controller

**Comment by edtjones** [comment]
@paul notes from our chat:

- see if we can gsub the searchable text in MySQL to be downcase a-z only before doing the LIKE query
- gsub the incoming query in params to match the same thing - so `St. Paul's` would become `st pauls` under all circumstances.
