### ISSUE TITLE
Overlays 'in this area' ?

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#78]
Possibly a bit confusing? What's the 'area' concerned? The project is about London, so I wonder if the default position is to have the full list, and then work on a solution that allows filtering if we need it later? Most of the overlays will be of London as a whole (increasing in size over time), while some will be patchy - RAF photos, local maps etc.

**Comment by foxpaul** [comment]
Changed "In this area" to "found". In phase 2, we will bound the overlay search to the viewport of the map
