### ISSUE TITLE
What do we do about poorly georeferenced RAF photos?

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#79]
I can see a few on the map at the moment which haven't been done very well - I guess this relates to the issue we've touched on before, i.e. active admin management of the site and content that's been uploaded. Thinking also of spurious and/or dodgy content!

**Comment by edtjones** [comment]
You can add more control points to an image as long as you have a georeferencer account. We'll do this:

- add a 'fix this' icon to the corner of each georeferenced image
- link to georeferencer to add more control points

**Comment by edtjones** [comment]
@mpdavies @selrashidi we would like to propose that for now we allow people to flag these images for your attention, rather than 'fix this'. You'll get an email with a link to the georeferencer image in question to fix up.

That ok?

**Comment by klokan** [comment]
@edtjones there is also "/review" function available for Georeferencer V3, which you could use to make quality control on the crowdsourcing. Documented in our Start document.
Could you please provide me with access to the live instance of your application?

**Comment by edtjones** [comment]
Thanks for the input @klokan - alpha site is as alpha.layersoflondon.org. Our development branch is rather ahead of the deployed code though; we need to do a deploy. Click the 'RAF photographs' overlay to see the georeferenced images.

I'm thinking about @mpdavies' team's time: we need to decide if active or passive moderation is required. My hunch for the georeferenced images is that post-hoc moderation is acceptable.

**Comment by mpdavies** [comment]
Thanks both. I agree with Ed. In this phase, with only photos for Barking and Dagenham, it's really about tidying up post-hoc, so having someone from the Layers team able to intervene and delete a photo and send it back to the georeferencer.

Petr: I'm going to get in touch soon about planning for phase 2, as we need to get plans and budgets in place for assessment by our funder.

**Comment by klokan** [comment]
@mpdavies - I am going to fly to London on Feb 10th+11th for #MapHackathon. Lunch / dinner? Write me an email please.

**Comment by edtjones** [comment]
Have added a flag
