### ISSUE TITLE
finding out how many images have been georeferenced and how many remain

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#8]
It would be good if this could be per Borough, as it would help us target our public engagement.

**Comment by mpdavies** [comment]
Ok, so there is a set of things that we need re. Georeferencer:
1) images to be organised into Borough folders, so schools etc can work on their local areas
2) could be combined with being able to click on the basemap to bring up a folder for the borough you are clicking in
3) it has to be possible to browse and select somehow
4)  some sort of count of photos done/remaining
