### ISSUE TITLE
how will school groups geo-reference

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#81]
From @amytodd - will there be a teacher log in and they will share that with pupils? at the moment everyone needs to sign up individually

**Comment by martincf** [comment]
For logging into Geoereferencer, at the moment, it's individual accounts not associated to the main app. If Klokan have some form of single sign on system, we may be able to implement it.

**Comment by amytodd** [comment]
Hi all - I think this is a priority in terms of asking Kolkan if this is possible, it is a barrier for new users to the website and being able to sign up with fb for example would be great.


Thanks

________________________________

**Comment by andyError** [comment]
@edtjones can we say how this will be handled now?
