### ISSUE TITLE
User data capture draft items

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#83]
From @selrashidi :

From Individuals:
Name
Email Address
First part of post code
 
Groups:
Name of group
Names of individuals within the group
Email Addresses
First part of Post Code
 
Schools:
Name of School
 
Year group/class/subject
Name and email address of teacher.
Do we need the email addresses of pupils?
 
 
Who will the information be shared with:

Names and email addresses:
Names of Schools and Groups, other project partners to be shared with
The London Metropolitan Archive, The Museum of London, the Heritage Lottery Fund, Potentially other project partners.

**Comment by martincf** [comment]
I presume this would be best captured via some form of questionnaire system, such as Survey Monkey?

**Comment by andyError** [comment]
I think this has been superceded.
