### ISSUE TITLE
Record flag/reporting system

### ISSUE THREAD

**Issue by martincf** [layersoflondon/application#85]
Should have:
list of issue type: low quality, offensive, inaccurate, copyright issue
More details

**Comment by martincf** [comment]
<img width="910" alt="screen shot 2018-08-01 at 12 14 05" src="https://user-images.githubusercontent.com/1022898/43518574-71723146-9584-11e8-8c1a-2cc7bc15c976.png">

Whether this is a floating box or replaces the record view, I'm not too sure.

**Comment by edtjones** [comment]
popover makes more sense - need the context of the record you're reporting

**Comment by martincf** [comment]
We've decided that a record will stay published when a user flags it as a concern. However, we do need to indicate that the record has been flagged and will be attended to. Probably a message near the flag facility saying so.

**Comment by andyError** [comment]
@phendrick @edtjones I'm going to wait for you to flesh to out before styling.

**Comment by phendrick** [comment]
there's a feature branch feature/report-records with a working form that you can get to via the record view (link in the footer)

**Comment by andyError** [comment]
Done.
