### ISSUE TITLE
Places pins are cropped

### ISSUE THREAD

**Issue by foxpaul** [layersoflondon/application#86]
![screen shot 2016-12-22 at 11 03 54](https://cloud.githubusercontent.com/assets/218674/21423700/59e31db4-c836-11e6-9460-ec83589690a9.png)

**Comment by andyError** [comment]
I need to talk to Paul about how these are configured. Note pins are <img>s, these are just <div>s, I'm not sure why they are different, we should probably implement them the same for consistency.
