### ISSUE TITLE
Adding a Tudor Map of London before June 14

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#88]
One of the Layers we should be adding is the Tudor Map of London. Matthew is trying to get a digital copy imminently as he is speaking about Layers at an event on June 14 (a launch of the newly printed version of that Tudor map). If we provide you with a digital version of the Tudor map, could you incorporate it before his presentation?

**Comment by selrashidi** [comment]
Yes!


Seif





________________________________

**Comment by Forester1** [comment]
We have the pdf copies of the map and I have contacted MOLA about the georeferencing. Will update asap

**Comment by Forester1** [comment]
Update: MOLA now have copies of the PDF version of the map and I am still chasing a high resolution original TIFF image if available.

**Comment by Forester1** [comment]
Update: High resolution original TIFF image of the Tudor map has been supplied for georeferencing

**Comment by edtjones** [comment]
Yep - I have it @mpdavies :) It'll be on the alpha site for definite. Are you presenting or will people be playing with it? if presenting, we might be able to get it on the beta site too.

**Comment by mpdavies** [comment]
Excellent - I'm just going to present the beta site, so if it's there then great - if zoom/opacity possible then that's even better. Not going to give URL out generally yet....

**Comment by edtjones** [comment]
We’ll do our best. There’s a lot of rough edges to knock off but it’ll be on the alpha for definite and the beta if possible.
