### ISSUE TITLE
Results list - overflow isn't sized properly

### ISSUE THREAD

**Issue by edtjones** [layersoflondon/application#88]
Something's broken the height of the results boxes.
![screen shot 2016-12-22 at 21 38 05](https://cloud.githubusercontent.com/assets/4377783/21441250/fb4caf5a-c88e-11e6-92d7-775315250728.png)

**Comment by edtjones** [comment]
This seems to be related to viewport height. With devtools open at the bottom on my 13" MBP I get that ^

**Comment by andyError** [comment]
Fixed.

**Comment by edtjones** [comment]
Yeah should be ok - I assume it’ll be georeferenced?

Ed

**Comment by mpdavies** [comment]
georeferenced map was received on Monday, so should be with Error? Can this please be added to the new website before 14 June?
