### ISSUE TITLE
Administrator level dataset upload for new records

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#89]
An administrator level function to import spreadsheets or CSV files is required so that new curated datasets can be pinned to the map. These tables will have a set of xy coordinates to allow the data to be easily imported as a geographic layer.
Formats could include csv, xls, geojson and also that the option is there for a flat text file with geographic coordinates or a prepared geographic point file such as kml. 
The key thing is a way for the administrator to quickly bulk upload a set of pins to the map as partners are providing curated quality datasets.

**Comment by Forester1** [comment]
@martincf and @phendrick When this is being tested let me know as I can supply some sample datasets that partners are keen to see.

**Comment by Forester1** [comment]
Can we get a milestone for testing of this? There is increasing number of partners datasets that require preparation and cleansing. Without access to the administrator bulk upload tools it is difficult to advise on this.

**Comment by edtjones** [comment]
Hi @forester1,

Presumably related to the first draft data schema you’ve sent today?

**Comment by Forester1** [comment]
Yes, but the wireframe today _Download_Wireframe_v0.1.pptx_ is the public download view of the permitted administrator bulk uploaded datasets and suitable collections.
