### ISSUE TITLE
would a modern satellite overlay be do-able in this phase?

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#90]
Like most basemaps, the one we're using doesn't show more than the outlines of buildings. So I was wondering whether there was scope to pull in a modern satellite layer so that the school kids can see how the landscape's appearance has changed since the 1940s photos... In Georeferencer for instance you can choose a satellite layer, and it's possible to see echoes of features that were there in the 1940s.

**Comment by edtjones** [comment]
Probably, @mpdavies - as an overlay like the aerial photos. Can you find one which has a friendly licence and a tile server? Will do a bit of legwork next week. 

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by mpdavies** [comment]
ok, will ask when back in the office. Georeferencer uses mapbox, which presumably is subscription. NLS has that and Bing. We used Google satellite for our locating london's past site - is that feasible?

**Comment by edtjones** [comment]
Yeah we could swap out the base layer for google maps if we wanted - but there is a limit on daily clicks which is why we didn't do that - we took the view that this should run independent of a third party licensing system as far as possible. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by edtjones** [comment]
@mpdavies I've done a bit of experimenting. We can do Google Satellite as a layer if that's ok?

**Comment by mpdavies** [comment]
Thanks! That would be good, at least for the time being while we test with schools and groups (so if there's a limit on clicks we can be careful how widely we publicise the alpha site). would be good to have both the satellite and street layers.

**Comment by edtjones** [comment]
No click counting on the google tiles as far as I can tell - I'll deploy to the alpha site on the next release

**Comment by edtjones** [comment]
Added

**Comment by Forester1** [comment]
Also worth considering for this map printing viewer issue:
- annotation tool
- popup arrow/speech bubble text tool
- copyright statement on map
- default site URL text 
- legend text
- default Layers of London logo

**Comment by selrashidi** [comment]
It is not urgent but important. (especially for researchers)


Seif


Seif El Rashidi

Project Manager, Layers of London

w:alpha.layersoflondon.org

The Centre for Metropolitan History

The Institute of Historical Research

Senate House, London WC1E 7HU

t: 02078628705

m: 07908126509

e: seif.elrashidi@sas.ac.uk



________________________________
