### ISSUE TITLE
Opacity slider

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#92]
A small point, but any chance the opacity sliders could work dynamically while the slide bars are moved, rather than after a level has been chosen?

**Comment by edtjones** [comment]
Might be possible @mpdavies but I suspect @foxpaul did it to avoid nasty flickering as it redraws the screen. Will investigate. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by edtjones** [comment]
Have fixed in development commit #fb62b965

**Comment by andyError** [comment]
Closing, dupe of: https://github.com/layersoflondon/application/issues/437
