### ISSUE TITLE
Editing notes

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#93]
Glad the edit feature's been added. Is it possible to make sure that files that were uploaded originally stay there? I edited a note and just changed some text, but it wanted me to upload another image to replace the one I had added before.

Also, would it be helpful to have a filter option (or even an overlay?) to show your own notes, perhaps in a different colour?

**Comment by edtjones** [comment]
Re 'your notes': for now we will be listing them on a page with your account details and stuff. Adding to the map isn't super easy at this point but definitely can be done in future. 

Re the image replacement - yes, we should be able to do something here I think. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by edtjones** [comment]
For @foxpaul - just remove the validation on the file if there's a file present.
