### ISSUE TITLE
Link checker

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#93]
What mechanism is in place to check for broken links/urls and repairing them? This is not so much of an issue now but as more content is developed it needs to be administered and quality assured.

**Comment by edtjones** [comment]
Are you just thinking of checking the url is returning 200OK and not a 404?

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by Forester1** [comment]
Both. The key concern is that as there is going to be such a large volume of curated and non-curated content and especially links to outside resources in the descriptive metadata can quickly becomes outdated or URLs not working.

**Comment by edtjones** [comment]
Would be relatively straightforward to hit a url included in structured content. If we allow urls in WYSIWYG content that would be harder. Suggest for now if we allow text formatting we don’t allow links. 

--
Sent from my phone: please forgive the brevity.

Ed Jones
