### ISSUE TITLE
Overlays not found after text searching

### ISSUE THREAD

**Issue by mpdavies** [layersoflondon/application#94]
On opening the map the two current overlays are both selectable. When I search for something within the area covered by one of them (Eg St Paul's) I get search results but there are three issues:

1. the red pins look strange...
2. The search engine is still not returning the 'note' I created about St Paul's cathedral
3. The overlays are no longer visible/selectable- they only appear if I clear the search box and press search. You'd expect to be able to select the Morgan overlay if you are looking at search results in/around the city of London for instance.

**Comment by edtjones** [comment]
Thanks for this @mpdavies. Will probably split into several tickets for clarity. 



--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by edtjones** [comment]
We're going to stop the overlays being searched when you make a text search - we only have 4 or 5 anyway - so the overlays will be available regardless of the search results.

Implementation notes for @foxpaul 
 - return the same set of overlays for all search results
 - when rendering the overlay list component, check to see which ones are checked in the store and re-check them
 - the net result will be the overlays will be unchanged across searches
