### ISSUE TITLE
Overlay order

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#95]
Can the overlay order of maps drop down please be in Chronological order please. Of the current list the order should appear as:

Morgan Map
Rocque Map
RAF Photos
Satellite View

**Comment by edtjones** [comment]
Hi @Forester1 - we plan to have a little tool to manage the z-index position. It's in 'layer tools' on the prototype.
![screen shot 2018-05-08 at 10 25 41](https://user-images.githubusercontent.com/4377783/39749309-406641a4-52aa-11e8-92a8-e8e5893414e5.png)

**Comment by Forester1** [comment]
Thanks @edtjones, Got it.
Will the button for "Layer Tools" and the "Done" button (at http://prototype.layersoflondon.org/pages/map) be modified for the next release as they are more difficult to find?

**Comment by andyError** [comment]
Yes, they will - this has been improved in latest development code.
