### ISSUE TITLE
Router only works with notes that are in the initial state

### ISSUE THREAD

**Issue by foxpaul** [layersoflondon/application#98]
the "pins/:id" route will only display a note if MapContainerStore.getState().markers contains a note with the specified :id 

If we can't find that pin, we should call a MapContainerActions action to fetch and display the note.

**Comment by edtjones** [comment]
@foxpaul I haven't bothered with an action in MapContainerActions. Instead I call `Pin.find()` directly in the router. Is that ok?

**Comment by Forester1** [comment]
Is there an update available for this? we need to get documentation through compliance at the moment so having this information sooner rather than later would be very beneficial. Thanks
