### ISSUE TITLE
Cookies information

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#98]
We need information on the cookies policy and cookies in use on the Layers of London website in order to compile part of the site's legal documentation. Including for instance

-What is being measured?
-Notifications
-What is being recorded
-What cookies are on the site?

Can you provide this please?

**Comment by Forester1** [comment]
@amytodd @KFlynn1 @selrashidi  FYI

**Comment by Forester1** [comment]
This is still required for site privacy policy. Can we get an update on this?

fyi @amytodd @KFlynn1 @selrashidi

**Comment by Forester1** [comment]
Linked to _Data collection question #159_

**Comment by edtjones** [comment]
@Forester1 can't really answer this in entirety 'til we have decided on any third-party integrations - for example, embedding audio and video files might well drop cookies.

For now, there are 2 Strictly Necessary cookies:

__cfduid - a Cloudflare cookie used for security tracking on our content delivery network: https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-CloudFlare-cfduid-cookie-do-

_layers_app_session - the session cookie used to identify a user in the application.

**Comment by amytodd** [comment]
On this can we confirm if we are going to be hosting through youtube/sound loud or if we will integrate this functionality into the site? (high priority for us to know this as we are having issues with permissions etc if working with 3rd parties)

**Comment by andyError** [comment]
@edtjones are we able to answer this now?
